### ISSUE TITLE
Import identity hangs after failed password attempt

### ISSUE THREAD

**Issue by jroedel** [kalaspuffar/secure-quick-reliable-login#126]
*Short description of the issue*
I tried to import my SQRL identity, but put in my password wrong.  It notified me of the problem but the dialog box didn't disappear and didn't let me continue. I'm using Android 6.0.1, Kernel 3.4.0-9723602

*Expected behavior*
Dialog box should disappear and allow user to try again

*Actual behavior*

![dialog](https://user-images.githubusercontent.com/3315281/38382548-c4d29656-38f9-11e8-9fe3-795ef699b038.jpeg)

**Comment by kalaspuffar** [comment]
Hi @jroedel.

Thank you for the bug report, exemplary. I've verified and fixed the issue. It should be fixed in the next release.

Best regards
Daniel
