### ISSUE TITLE
Small remark re.  Help

### ISSUE THREAD

**Issue by IvarSnaaijer** [kalaspuffar/secure-quick-reliable-login#154]
You mention the 77 digit number. I recall that it recently changed to 78.
To make it easier on you might even call it differently. Like 'huge' and only explain once that 'it is xxx bits or about 78 digits'. (I forgot the bits). I'll reread it later and compare it to what Steve does. But is is also more technical in his writing...

**Comment by kalaspuffar** [comment]
Hi Ivar.

Thank you for testing my application and thank you for taking the time.

If you want to help me out in fixing text appearing in the application the easiest way is to sign up to POEditor as a contributor and change the strings there. I will add the translations back into the application more regularly from now on as I'm beginning to become feature complete.

One of the main things I have in my pipeline is to go over all texts in POEditor at a later date but if you want to give me a head start then I would greatly appreciate it.

https://poeditor.com/join/project/Jlsa1tqxlx

Best regards
Daniel

**Comment by IvarSnaaijer** [comment]
Great. I'll do that and translate to dutch as that is my native language.

Op wo 2 mei 2018 17:45 schreef Daniel <notifications@github.com>:
