### ISSUE TITLE
When clicking the back button, the app opens the same page #bug

### ISSUE THREAD

**Issue by ahyar92** [kalaspuffar/secure-quick-reliable-login#174]
#### Expected behavior
Supposedly, When I hit the back button, the app will exit and will not show the same page.

#### Actual behavior
When I try to see the in-app features, and when I want to exit the app. Suddenly when I hit the back button, the app continues to display the same page.

#### How to reproduce
1. Install and open the app
2. Once inside the app, please press the back button on your smartphone, then you will see the app will not come out and display the same page.

----
- Device: Xiaomi Redmi 4X
- Operating system: Marshmallow, 6.0.1 mmb29m (CPU: Octa-core Max 1.9 GHz, RAM: 2 GB)
- Application Version: 0.7.1 (Varies by device)

#### Recording Of The Bug
https://www.youtube.com/watch?v=7J97aY1NXEA

**Comment by kalaspuffar** [comment]
Resolved.
