### ISSUE TITLE
manual language change

### ISSUE THREAD

**Issue by jroedel** [kalaspuffar/secure-quick-reliable-login#202]
### Feature request.
Option to manually change the language from the default OS language

*Use cases*

It's probably not a common problem, but if it would be easy to fix, I have my Android language in German to practice, but to read complicated explanations I change apps to English.

**Comment by kalaspuffar** [comment]
https://stackoverflow.com/questions/2900023/change-app-language-programmatically-in-android

**Comment by kalaspuffar** [comment]
Available in next release.
