### ISSUE TITLE
chore: make SQRL icon on main page less blurry

### ISSUE THREAD

**Issue by sesam** [kalaspuffar/secure-quick-reliable-login#208]

**Comment by kalaspuffar** [comment]
I think this is the same issue as the vector drawable issue.

At the moment we use the app icon distributed with app. On my phone 512x512 and sharp but different phones require different sizes so this is not optional when the svg is available.

**Comment by kalaspuffar** [comment]
I've updated the version on google play now with SVG for the main icon in the application and also for use as icon around the application.

Is it less blurry now?
Does it work for you?
I've tested on two phones (Pixel 2, Samsung Android version 16)

**Comment by sesam** [comment]
Looks fixed to me!
