### ISSUE TITLE
bug: unreadable tooltip during new identity creation

### ISSUE THREAD

**Issue by sesam** [kalaspuffar/secure-quick-reliable-login#210]
### Issue or error solving.

While creating a new identity and entering passwords, there is an empty tooltip that probably is supposed to have text like "Passwords do not match" or similar.

*Steps to reproduce*
1. create new identity
2. enter password and repeat password where they are (possibly either) not good enough or not second field is not repeated correctly

**Comment by kalaspuffar** [comment]
Should be fixed in the next release.

**Comment by kalaspuffar** [comment]
New release out, please try.

**Comment by sesam** [comment]
Fixed :)
