### ISSUE TITLE
chore: app icon

### ISSUE THREAD

**Issue by sesam** [kalaspuffar/secure-quick-reliable-login#212]
Suggestion: make an app icon that is (slightly) different from the official SQRL logo.

Maybe just add something to show this app's specialization?

This way
1. it shows the app is not "official"
2. more importantly, it separates the app slightly from other projects doing similar apps, like the seemingly abandoned other android impl.
3. it's one way we can create user happiness :)

Adding some crazy brainstorming, if there is interest to be more creative:
- the original SQRL icon, with some color variation
- the original SQRL icon, but less complicated
- the original SQRL icon, but zoomed in on some part
- the original SQRL icon, but with more life-life squirrel and a more easy to see padlock
- a squirrel steals/eats up passwords, leaving only nuts behind
- a trail of nuts leading to a barricaded password store
- a lock-icon that is opened up (like a nut?) and a squirrel is inside, carefully guarding some secrets
- ...

**Comment by kalaspuffar** [comment]
Great suggestions. At the moment the only other Android application don't use the official icon.

I'm not a designer so I can't do any of the suggested changes and you need to see it to like it. 

My favorite suggestion was to keep the logo but use a more animated squirrel. 

Then again I would love to keep it vector based so I could keep the application size small.

**Comment by sesam** [comment]
more animated? reminds me of this: https://media.giphy.com/media/l3vRfMU8y5ayXIWkM/200w.gif

**Comment by kalaspuffar** [comment]
Well, maybe not animated as in moving. But more life like, more colors. 

But it would be fun with a tadada animated gif :)

**Comment by sesam** [comment]
I like the icon now that it's bigger, and due to new insights into app marketing I'm withdrawing the idea to change the icon. Basically until SQRL is *very* well-known we'll likely want to be as similar to other SQRL things as possible. So I'll close, at least for now.
