### ISSUE TITLE
bug: scan identity -> back -> decrypt fails

### ISSUE THREAD

**Issue by sesam** [kalaspuffar/secure-quick-reliable-login#215]
### Issue or error solving.

Back-button is causing unexpected effects on screens:
- after encrypting newly created ID (before saving)
- on Scan QR screen

*Steps to reproduce*
1. I started creating an identity and completed the slow encryption step
2. then tapped Back
2. Then chose to scan a QR
3. then tapped Back (didn't find the QR printout)
4. then the app said "scan successful"
5. then I entered the password of the just created profile (fingers crossed)
6. then decryption+encryption failed

**Comment by kalaspuffar** [comment]
A really complex error you found there :)

I think the best solution would be to end up at the main screen if pressing back after identity creation.

I was actually able to enter the correct password after the "scan" step and got the identity imported/created twice :)

**Comment by kalaspuffar** [comment]
Well if you press back there now you will exit the application, seems most reasonable. You are passed the point of no return :)

**Comment by kalaspuffar** [comment]
Will be in the next release.

**Comment by kalaspuffar** [comment]
New release out, please try.

**Comment by sesam** [comment]
yes, sorry for the complex repro steps. On release 12.1 the primary bug is still there.

Repro: 
1. Advanced - Import
2. press Back on the scan screen
 => input password screen is shown (while toast says "Scan cancelled")
On the input password screen I didn't try entering any password.

**Comment by kalaspuffar** [comment]
Great catch. This other place should also be solved in the next release :)
