### ISSUE TITLE
Bug: crash on old devices

### ISSUE THREAD

**Issue by kalaspuffar** [kalaspuffar/secure-quick-reliable-login#217]

**Comment by sesam** [comment]
I've got old devices. Which OS / CPU / something would you want this to be tested on? Then `adb logcat`?

**Comment by kalaspuffar** [comment]
That would be appreciated, I have a device with the problem but the logcat output made no sense.

As I'm a bit sick and wanted to release the Biometrics and other bugfixes I just reported this to myself as a reminder.

Might look more into this tonight so if you can give me more visibility with more devices that would be helpful.

My approach otherwise would be to comment out functionality until the error disappears. :)

**Comment by kalaspuffar** [comment]
Seems like I found the error.

Devices before Lollipop could not use vector drawables for notifications. All other icons and stuff could be used as vectors but there you needed PNG. So I created a notification image for that purpose.
