### ISSUE TITLE
bug: change of translation does not change all labels

### ISSUE THREAD

**Issue by IvarSnaaijer** [kalaspuffar/secure-quick-reliable-login#218]
The blue bar with SQRL - avanced features does not change when I change the language. This happens with other blue fields too.

**Comment by kalaspuffar** [comment]
Are you sure it has been translated?

Check in poeditor for reference and if text translation is missing then please provide some :)

**Comment by kalaspuffar** [comment]
My plan upon release to hide languages with less than 90% translation.

**Comment by kalaspuffar** [comment]
Sounds bad.

What language is default on the phone and what is selected in the language select menu?

**Comment by IvarSnaaijer** [comment]
Default language is Dutch, when I set it to English, the Title of the various screens is still in Dutch. (Advanced Functions, Export, Rename identity etc)
