### ISSUE TITLE
feat: make current identity visible on main login screen

### ISSUE THREAD

**Issue by IvarSnaaijer** [kalaspuffar/secure-quick-reliable-login#220]
Currently we can not see the current identity used on the main screen. 

If I recall correctly this becomes apparent later but it still would be usefull

**Comment by sesam** [comment]
While the idea with SQRL is that you only ever need one identity, at least while testing it would be practical to see what identity is being used.

The QR scan view currently shows one text "Scan QRCode for site" and maybe that is a quick and good enough place to add in a (name of identity) at the end.

Another idea is to put the chosen identity at the top of the front page where it currently says "SQRL - Main". I don't know Android design guidelines, but probably changing that header text to `(identityname) - (app name)` could be ok.

**Comment by IvarSnaaijer** [comment]
I'm still conflicted. Possibly this does need to go to a three stripes menu in the top left corner (like Google does), in my current proposal it is rather prominent. You could make it clear to users that creating a new identity should not be necessary in the ´create´ window (by giving use cases), and only show the selection when there is actually something to choose.
