### ISSUE TITLE
bug: lastpass is triggered by settings window

### ISSUE THREAD

**Issue by IvarSnaaijer** [kalaspuffar/secure-quick-reliable-login#221]
For some reason LastPass thinks there is something to remember on the settings screen. It points to  sqrl.ea.org for the field  'password verify'

**Comment by kalaspuffar** [comment]
Don't have LastPass installed on my dev devices but I'll try it.

**Comment by kalaspuffar** [comment]
I renamed the field and installed LastPass, didn't trigger for me but hopefully, you'll be able to test after next release.

**Comment by IvarSnaaijer** [comment]
I tried 0.12.2, but it has the same problem. (not sure if it is an update as I forgot to mention the version in my previous report like a total noob.

**Comment by kalaspuffar** [comment]
Just by chance, you're not an Android developer, are you? 

I feel that this bug is a bit hard for me to debug as I'm not really triggering it.

I could try it on more devices with LastPass perhaps. Or ask a colleague to look at it.

**Comment by IvarSnaaijer** [comment]
It has been quite some time, I have to setup the whole development stack again.

**Comment by IvarSnaaijer** [comment]
I've created a case @ Lastpass, and they have forwarded it to level 2. I'm happy to see thst they take it seriously. I'll keep you posted.

**Comment by IvarSnaaijer** [comment]
How is the password dialog implemented in the settings dialog. Is it completely separate or somehow hidden, and floats when pressing save? I have send them a video with the problem.

**Comment by kalaspuffar** [comment]
Hi Ivar.

If I have understood you correctly it's this field you are talking about.

```
    <EditText
        android:id="@+id/txtSettingsPasswordVerifyInSeconds"
        android:layout_width="0dp"
        android:layout_height="48dp"
        android:layout_marginEnd="16dp"
        android:layout_marginStart="16dp"
        android:layout_marginTop="8dp"
        android:ems="10"
        android:inputType="number"
        android:nextFocusDown="@+id/txtSettingsIdleTimeout"
        android:hint="@string/settings_password_verify"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/textView11"
        tools:ignore="TextFields" />
```

https://github.com/kalaspuffar/secure-quick-reliable-login/blob/master/app/src/main/res/layout/activity_settings.xml

**Comment by kalaspuffar** [comment]
https://drive.google.com/file/d/18_X-HBWe8-CSrkoXGd3G6Jj3MaQe2bK2/view?usp=sharing

**Comment by IvarSnaaijer** [comment]
This the answer I got from Last pass: 
Thanks for reaching out to LastPass support!
Our development team have reported this issue as an Android issue in our LastPass application. Android is prompting this notification for LastPass when it is not true. We have already reported this to Android for them to take a look and investigate further. You're more than welcome to report the same issue to Android to raise the awareness. Thank you for spotting this on your end.

**Comment by kalaspuffar** [comment]
Hi Ivar

Great, I was really wondering if there was something I had done incorrectly. We will keep an eye on it but hopefully, they'll find a solution to this problem.

Best regards
Daniel

**Comment by IvarSnaaijer** [comment]
I was finally able to get Android Studio working. I did not point it to the Trunk, when I did It immediately started to complain about NDK and CMake. After installing those I was able to see the dialogs. 
But back to the issue at hand: My A-Studio (3.3.1) complained about a missing attribute : 

android:importantForAutofill="no"
It put it just under android:hint

**Comment by alexhauser** [comment]
@kalaspuffar, I guess this one can be set so solved/closed?!
