### ISSUE TITLE
ui more layered

### ISSUE THREAD

**Issue by IvarSnaaijer** [kalaspuffar/secure-quick-reliable-login#222]
The current layout is a bit technical. I propose a few more layers. 
Make advanced settings just settings. 
Make settings 'security'
Float identity selection to main screen
Make a 'manage identities' button (give it the identity selection)
Move import export rekey change password create new under manage
Move import from text under import (add a button to camera or add an extra submenu.

This removes the more technical parts from the casual user, and gives more room for some explanations.

**Comment by kalaspuffar** [comment]
Could you make some mockups to visualize your thoughts?

**Comment by kalaspuffar** [comment]
Maybe you can checkout issue #213.

Sesam have already started this discussion, you may find a diagram and some other good resources over there.

**Comment by IvarSnaaijer** [comment]
Duplicate of #213
