### ISSUE TITLE
feat: Can't distinguish multiple identities if they have the same name

### ISSUE THREAD

**Issue by sesam** [kalaspuffar/secure-quick-reliable-login#223]
### Issue or error solving.

It's possible to create new identities with the same name, and then I don't see how I could distinguish them, or know which is currently selected. I also don't know the sort order used (if defined).

*Expected behavior*
Either disallow user to mess up like this and create support tickets :), or make it more distinguishable which is which.

*Steps to reproduce*
Create two identities and name them the same. Or rename an existing identity so it gets the same name as some other existing identity.

I'm leaning towards not allowing several identities with the same name, i.e. the Windows/MacOs way, just tack on a (1) or (2) at the end if the name is occupied.
Algo could be:
```
unique_name(name, index = 0):
   newname = index == 0 ? name : name + "#" + index
   return newname in existing_names ? unique_name(name, index+1) : newname
```

**Comment by kalaspuffar** [comment]
Should be solved in the next release.
