### ISSUE TITLE
feat: Identity names can be too long to show

### ISSUE THREAD

**Issue by sesam** [kalaspuffar/secure-quick-reliable-login#224]
### Issue or error solving.

It's possible to give an identity a really long name, which then can't be displayed.

Maybe limit length to around 16 chars.

16 repetitions of W fills the screen width on a narrow device.

**Comment by kalaspuffar** [comment]
Maybe restrict with ...

ThisIsAReallyLo...

**Comment by kalaspuffar** [comment]
Maybe this might not be an issue. I created a really long name and I feel that even though it looks a bit wonky it can handle the name correctly and if you flip the screen you can read the full name.

So what problem should I solve? I would rather not create an arbitrary restriction if not needed.
