### ISSUE TITLE
bug: The vertical eclipse is not visible in 0.12.2

### ISSUE THREAD

**Issue by IvarSnaaijer** [kalaspuffar/secure-quick-reliable-login#229]
The three dots at the top right are not visible on my Galaxy S7, but the region functions as if it is there.
They show fine on a Tab 2 with 0.12.1
![gs7](https://user-images.githubusercontent.com/18215506/49898524-2d436e00-fe51-11e8-8597-a49f0cd00786.jpg)
![tab2](https://user-images.githubusercontent.com/18215506/49898527-2f0d3180-fe51-11e8-82ed-fa74b575e0e0.jpg)
I updated to 0.12.2 on the tab and now the translation is ok, but the eclipse is gone.

**Comment by kalaspuffar** [comment]
Should be restored in new version 0.13.0

**Comment by IvarSnaaijer** [comment]
Fixed
