### ISSUE TITLE
Password screen gets obscured by keyboard

### ISSUE THREAD

**Issue by IvarSnaaijer** [kalaspuffar/secure-quick-reliable-login#231]
When the password screen pops up and my keyboard is invoked it obscures the button. Adding an image seems to be too hard for me... my keyboard is the default Samsung one. It covers almost half the screen.

**Comment by kalaspuffar** [comment]
Moved the login popup to top so this might be fixed in the next release 0.13.0

**Comment by IvarSnaaijer** [comment]
Great, I can now see what I'm doing.
