### ISSUE TITLE
Bug: Save file does not work, permissions denied.

### ISSUE THREAD

**Issue by kalaspuffar** [kalaspuffar/secure-quick-reliable-login#232]

**Comment by IvarSnaaijer** [comment]
I was just trying to export with 0.13.1 and got an error (indicating diskspace)

**Comment by IvarSnaaijer** [comment]
This looks like a duplicate of #209

**Comment by IvarSnaaijer** [comment]
Tested in 0.13.3  fixed

**Comment by sengsational** [comment]
This can be closed as it was a duplicate of #209
