### ISSUE TITLE
Issue authenticating to SQRL Service Provider API Demo & Exerciser

### ISSUE THREAD

**Issue by acr-varonis** [kalaspuffar/secure-quick-reliable-login#234]
Hi there,

Seems like the android SQRL client cant authenticate to the SQRL Service Provider API Demo & Exerciser -  https://sqrl.grc.com/msa

The error message I see on the android app is:
Transient error: the server indicated that the signature(s) are correct, but something about the query prevented the command form completing.

Thanks.

**Comment by kalaspuffar** [comment]
Hi @acr-varonis 

Have you tried with 0.13.1 ?
We had an issue with the new servers handling the IP check differently.

Best regards
Daniel

**Comment by IvarSnaaijer** [comment]
I just tested the site with 0.13.1 
Works.

**Comment by acr-varonis** [comment]
I can confirm this issue was resolved on 0.13.1.
Thanks.
