### ISSUE TITLE
QR import problem

### ISSUE THREAD

**Issue by kalaspuffar** [kalaspuffar/secure-quick-reliable-login#236]
Reported from Papa Oz

Import from QR: Did not succeed. The app reads the QR a few times, then I get a black screen. Lightning QR suggests that the phone was locked by another app.  (He also mentions that he does not lock the phone. Maybe your app does not need to do that either.) I had to reboot the phone. Lightning QR can read the my ID QR.  It bears the initial signature "sqrldata)".  The rest is, of course, encrypted.

**Comment by alexhauser** [comment]
Hi @kalaspuffar ,

I think without having the QR code in question at hand, this will be impossible to debug. Do you know if it's available somewhere?

On the other hand, given that this seems to be the only report for this issue so far and QR code scanning is working for everyone else, we might also consider treating this as a non-issue and closing this for now.

Best regards,
Alex

**Comment by kalaspuffar** [comment]
Sounds reasonable.
