### ISSUE TITLE
Stack Traces on Startup

### ISSUE THREAD

**Issue by sengsational** [kalaspuffar/secure-quick-reliable-login#246]
*Short description of the issue*
Stack traces on startup of the app: `NoClassDefFoundError`
*Expected behavior*
Maybe just logging instead of stack traces?  Maybe this is not really a problem.  Or maybe it's just an artifact of how I've configured the project?
*Actual behavior*
When I started the app for the first time, the Logcat gets lots of NoClassDefFoundError stack traces (see here: https://github.com/sengsational/secure-quick-reliable-login/wiki/Logcat-with-NoClassDefFoundErrors).
*Steps to reproduce*
I forked the project, pulled the project into Android Studio 3.3.1, then ran it on my device "Moto G (5) Plus (Android 8.1.0, API 27)".

**Comment by kalaspuffar** [comment]
Hi @sengsational 

Well, these errors will not be my main focus for a while. But as you have the Studio up and running if you like you may see if you can rectify them for us. Pull request are most welcome :)

Best regards
Daniel

**Comment by sengsational** [comment]
It looks like if there's even a sniff of biometrics in an activity, the Android platform tries to exercise it, even though the method containing the code is never entered.

I found this [https://stackoverflow.com/questions/52896090/authenticationcallback-and-keygenparameterspec-crashing-app-despite-checking-api] which shows how in that case, if the biometric stuff is pulled out into a separate class, the problem is alleviated.   I'm not sure right now how to apply the knowledge to the code in SimplifiedActivity, but I'll think more about it.

**Comment by sengsational** [comment]
I was able to get past the biometric stack traces by moving the biometric stuff into a new class only to realize that there was another problem " ClassNotFoundException OnUnhandledKeyEventListener", being discussed here: https://stackoverflow.com/a/52954286/897007 and here: https://issuetracker.google.com/issues/120750246

The good news is it's just junking up the very early bit of Logcat and the app works.

**Comment by sengsational** [comment]
So there were two things causing stack traces in the Logcat on startup 1) Biometric stuff and 2) OnUnhandledKeyEventListener.

I found a solution to 2) here: https://stackoverflow.com/a/42957234/897007

So I moved the biometric stuff out into a separate class again (called it `LoginActivityHelper`).  At first, I tried to put it in the super class (`LoginBaseActivity`), but when I did that, the stack traces still were happening.  Only when it wasn't in a class that did not extend `Activity` does it remove the stack trace on startup.

I'll make a pull request shortly.  It should not change the operation of the application at all, but just make it nicer for developers that might come along.

**Comment by alexhauser** [comment]
Hi @kalaspuffar ,

I guess this one can be closed as well, as discussed in the corresponding PR.

Best regards,
Alex

**Comment by sengsational** [comment]
I'm still not pleased with having stack traces at all, but as I mentioned, I think it's really Google's problem to fix; all we could possibly do are the work-arounds that are goofy looking in our code.
