### ISSUE TITLE
Improve login experiance

### ISSUE THREAD

**Issue by kalaspuffar** [kalaspuffar/secure-quick-reliable-login#252]
Reported by @sengsational

On the Android app, I clicked "Advanced Functions > Use Identity" (probably needs to be moved to the main page at some point), and it was obvious I needed to scan the QR code on this site's registration page. The app flipped back out of camera mode. Then it's asking for a "password". Here I found myself wondering "does this app think I already have a password for sqrl.grc.com? And I'm thinking "whoa, I'm not giving my SQRL master password to this hinky forum site, who knows who this Gibson character is, anyway" ;) Seriously, the point I'm trying to make is that instead of "password", it should probably be labeled "SQRL Master Password" and have an info thing that pops up and says "your master password is used to decrypt your identity...it won't leave your phone". Of course I realize that this UI / usability stuff is icing on the cake, but since I have "new eyes" today, I figured I'd write my "new eyes" reaction to today's version of the application. Certainly no malice intended.

**Comment by kalaspuffar** [comment]
Change label and perhaps add text to login button.

**Comment by IvarSnaaijer** [comment]
I opt for a label "Login with:" and the currently selected handle.

**Comment by kalaspuffar** [comment]
Hi @IvarSnaaijer

Sounds great.

I've added the term in POEditor but ended my dev time for today. 

Added alternative identity as a first draft. :)

Best regards
Daniel

**Comment by kalaspuffar** [comment]
![](https://s3.amazonaws.com/assets.mockflow.com/app/wireframepro/company/Cc09d9f00343be5aa571cc840f3472f46/projects/Mf421dde088ed6d581c66618009e730f21551597018478/pages/e80320270a0c4609a49206bd7ebe9c09/image/e80320270a0c4609a49206bd7ebe9c09.png)

**Comment by IvarSnaaijer** [comment]
Yes, especially the box will inform the user in a pleasant way that this is actually a big button. The new label (Tools/Setup) also is an improvement. I hope to find those soon in PO Edit.

**Comment by sesam** [comment]
A suggestion: buttons usually have the text under the picture, so if we want people to understand this as a button and not a modal-looking dialog window, it probably should look more like https://www.google.com/search?q=android+icon+button+with+text

**Comment by sengsational** [comment]
When I wrote:

>  I clicked "Advanced Functions > Use Identity" (probably needs to be moved to the main page at some point)

That was because I didn't understand that the big SQRL logo on the main page was actually a button, hehe!

**Comment by IvarSnaaijer** [comment]
No problem. And as you probably noticed, we more or less agree this is a design problem. It has to be obvious that it is a button, without being annoying. kalaspuffar even reached out to Steve Gibson, and he has in turn requested input from the whole Security Now listener base. So I expect some more input from professionals in this field. ;) @kalaspuffar brace for impact

**Comment by alexhauser** [comment]
Hi @kalaspuffar ,

I guess this one is obsolete by now and can be closed, would you agree?

Best regards,
Alex
