### ISSUE TITLE
Feature request for entering data into textboxes

### ISSUE THREAD

**Issue by Sliicy** [kalaspuffar/secure-quick-reliable-login#262]
### Feature request.

Is it possible for the text fields to *"jump"* from one field to the next when being asked to verify the long key? Sort of like how when you enter a serial key (in Windows, Adobe, Steam, etc.) when you enter information in one textbox, the next textbox is automatically selected?
This would make it easier when re-entering the number, enhancing the experience.

**Comment by kalaspuffar** [comment]
Hi @Sliicy 

Great suggestion. If you are talking about the Rescue Key / Recovery Key then it should already be implemented that way. Might differ depending on software model and there might be a place I forgot to add it but the intention is for this behavior where possible.

Best regards
Daniel

**Comment by silversword411** [comment]
Just setup new identity, thought this same thing. 

I think they're referring to the Create Identity | Enter Rescue code confirmation page per your wiring diagram:
https://sqrl.grc.com/threads/ux-help-welcome.397/

**Comment by silversword411** [comment]
Tested with latest version, still having problems.
![Screenshot_20190405-091104](https://user-images.githubusercontent.com/13395348/55655932-8a2db000-57c3-11e9-98af-e0a131519026.png)

**Comment by kalaspuffar** [comment]
Hi @silversword411 

In this screenshot, I can't see the keyboard so I don't know if the action button is a next field or a done button.

I have verified that this works on 3 different emulators and 6 phones so some Android models implement this feature.

Is this something that is missing in one spot or all of the entry fields for rescue code parts?

Best regards
Daniel

**Comment by silversword411** [comment]
Aah, I think we're referring to two different functionalities.

We're assuming that we type in the first 4 numbers, it's going to "jump" and either:
character focus automatically jumps to the Part 2 when it validates the first 4 characters when they're correctly entered without the enter/submit key
or
when you type the 5th character it'll appear in the Part 2 area automatically without the enter/submit keyboard entry (are you going to stop the 5th key entry if the first 4 were invalid?)

You're testing with the keyboard (numberpad's) next field function (which does move it to the next field)

The more seamless method is auto-validation and moving the character insertion between each of the Part fields automatically.

Of course testing this validation field some more:
Keyboard Enter does move the character insertion point to the next field no matter what (right, wrong, only 1 character etc). 
It does indicate when you get it wrong though only when you put 4 characters into any one field (and then only indicates the error with the red in the first field.

![Screenshot_20190408-040104](https://user-images.githubusercontent.com/13395348/55708063-063a1a80-59b3-11e9-9474-a64543c8742b.png)

**Comment by kalaspuffar** [comment]
Hi @silversword411 

Ahh, great. Thanks for the clarification. You are right.

We might look into switching field automatically on correct validation.

Best regards
Daniel
