### ISSUE TITLE
"Ask" results in infinite loop

### ISSUE THREAD

**Issue by shanedk** [kalaspuffar/secure-quick-reliable-login#266]
When using the ASK facility at https://www.grc.com/sqrl/ask.htm, the buttons come up over and over again no matter which one is pressed or how often. The diag webpage confirms that the proper button response was received and login was successful, but the app just keeps pulling up the buttons again.

Expected behavior: App goes back to home screen.

Actual behavior: Although the login works with the proper button response, the app keeps showing the buttons over and over again.

Steps to reproduce:

1: Go to https://www.grc.com/sqrl/ask.htm and fill out the form
2: Scan the QR code with the app
3: Respond to the ASK dialog by tapping one of the buttons

**Comment by sesam** [comment]
Using last public release of this app, I don't see buttons.

1) In web: By clicking the sqrl code, I do get redirected. On second attempt (already having a nut) the app flashes a selfie-cam view (I see myself momentarily) and then it logs in. Very strange.

2) Using the app, with the web page open on another device, I get the browser just reloading. But I still don't see buttons 1 and 2, just Login. After having a valid nut, it again shows the selfie cam view monentarily, then shows the logged in screen.

I guess the buttons are from apps built from source only? And that would mean the seen reload-bug (could be that it's just not implemented) are older than the latest commits.

**Comment by shanedk** [comment]
> I guess the buttons are from apps built from source only?

No, I'm using the version from the Play Store.

**Comment by sesam** [comment]
I tried a few times. Only get to log in, never get any buttons shown.
Diagnostics:
https://drive.google.com/file/d/1RCPW_HSK-czpy48hD32Ae-n-3WczrEg2/view?usp=drivesdk

**Comment by sengsational** [comment]
I must admit to being completely in the weeds about how or what to test with this "ask" thing.

At first, I went to the ask page on my browser put in some nonsense and hit the 'submit ask params', at which point is says "This session's previous SQRL transaction log is currently empty. Authenticate with your SQRL identity to create a SQRL transaction log for display and examination:"

Ok, so I scan the QR code with the client and it shows a diagnostic page with 2 transactions.  Nothing looks "bad", but, well, what's the take-away?

Then I figure, maybe it only works on same-device.  So I go to the ask page on my phone's browser,  put in some nonsense and hit the 'submit ask params'.  Again,  "This session's previous SQRL transaction log is currently empty...", and I touch the QR code, and it goes to the diagnostic page again.

Like I said, I don't get it.

**Comment by sesam** [comment]
@shanedk what are your steps to reproduce getting the ask buttons to show?

**Comment by alexhauser** [comment]
Is this issue still valid or did @kalaspuffar's commit solve it?
I tried reproducing it today but only got expected behaviour. Can this issue be closed?
