### ISSUE TITLE
TwilightManager spamming the logs

### ISSUE THREAD

**Issue by sengsational** [kalaspuffar/secure-quick-reliable-login#269]
Android is putting a repeated warning in the logs from TwilightManager (see: https://stackoverflow.com/questions/55290027/how-to-turn-off-twilightmanager-logging)

Expected: No repeated warnings

Actual: This message is repeated often:  "TwilightManager: Could not get last known location. This is probably because the app does not have any location permissions. Falling back to hardcoded sunrise/sunset values."

To Reproduce: Run the app and look at Logcat output.

Discussion:  One line of code could "solve" the problem: 
`AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO);`
This line, placed in the first activity, seemed to resolve the problem.

But I suspect that the root cause of the problem is that `styles.xml` uses `Theme.AppCompat.DayNight.DarkActionBar`.  That "daynight" thing is what gets Android to check location to see when sunset is.  But we probably do not want to add a permission to the app for location simply to allow the theme to change at dusk.  So possibly changing this theme is in order? 

I suggest we leave the style and run the `MODE_NIGHT_NO` until we get the UI design completed.

**Comment by kalaspuffar** [comment]
The reason I added dark mode is for people with photophobia. Maybe the app should be light and we add a switch to switch dark.

I just wonder if the accessibility feature for photophobia needs a dark theme to work well. Otherwise we just remove it.

**Comment by sengsational** [comment]
The question about whether to support both a light and dark mode might be best addressed in the future, when we have a proven UI guru working on it.

Temporarily, for now, setting `MODE_NIGHT_NO` will quiet the TwightlightManager complaints in the log.

**Comment by kalaspuffar** [comment]
Well, does the TwightlightManager impact the end user?
Photophobia is impacting users, does not have anything to do about UI. Yes, you need to keep that in mind when you create a UI but it's a feature I want the application to have.

Maybe you could change the configuration so it only uses the phone time instead of looking at GPS data.

**Comment by sengsational** [comment]
This does not affect the users, only the people looking at the logs.

My conclusion is that it's not consistent to use a `DayNight` theme without giving the app permission to location, but that it does default to hard-coded sunrise/sunset values, so the theme could be somewhat effective, as-is.  I did not see any way to specify in advance to use hard coded sunrise/sunset values.

All that being said, this is a problem affecting only developers, so can be ignored / closed.
