### ISSUE TITLE
Quickpass cleared when web site rejects

### ISSUE THREAD

**Issue by sengsational** [kalaspuffar/secure-quick-reliable-login#272]
Short Description: Quickpass removed even though user typed proper password

Expected: Quickpass stays active unless the user types the wrong password

Actual: Quickpass removed if the app shows "SQRL was unable to login to this site..."

Steps to reproduce: 

1. App open and quickpass active
2. Go to sqrl.grc.com (not authenticated)
3. Click login
4. Capture the QR code in an image editor
5. Scan the QR code
6. Type the quick pass (logon succeeds - expected)
7. Scan **that same QR code again** (from your image, captured in step 4)
8. Type the quick pass (logon does **not** succeed - expected)
9. The error SQRL was unable to login to this site..." shows (expected)
10. Dismiss the error message
11. Scan Scan that same QR code again
12. The app asks for the full password (unexpected)

Discussion:
This may be desired behavior,  but seems illogical to punish the user if the site is returning an error.  It's expedient to remove quickpass on all errors, but I'm not sure it's logical.

The only reason I even ran into this error was because I was trying to find an expedient way to test cases where quickpass goes away unexpectedly, so this would be very low-priority compared to other features/bugs.

**Comment by kalaspuffar** [comment]
Hi @sengsational 

You are right that we should only clear on decryption problems.

Not important but good practice.

Best regards
Daniel

**Comment by sengsational** [comment]
Resolved.
