### ISSUE TITLE
Old APIs show green robot launch icon

### ISSUE THREAD

**Issue by sengsational** [kalaspuffar/secure-quick-reliable-login#283]
*Short Description*
Default green robot launch icon shows on "old" API versions.

*Expected behavior*
Blue squirrel icon shows on all versions.

*Actual behavior*
Daniel saw the green robot on API 18.  I saw the "green robot" on the API 16 emulator.   

*Steps to reproduce*
Run the app on a device or emulator running an old API and look at the launch icon.

*Discussion*
I tried removing `vectorDrawables.useSupportLibrary = true`  from `build.gradle`.  The result was that on the API 16 emulator, **the standard sqrl icon did show properly**.  This standard (not round) is expected since `android:roundIcon` was added in API 25.

This post: https://stackoverflow.com/a/47910420/897007 indicates that removal of the support library will enable **build-time PNG generation for vector drawables for API levels lower than 21**.

So although we could remove that support, I have proven it would increase the size of the APK file.  My quick experiment showed that the APK was "3,517KB" without the support library and "3,490KB" with the support library.  These APK's were generated using the `Build > Generate Signed APK/Bundle` process.

I recommend that we leave the situation as-is; accept that old OS's will see the green robot.

**Comment by kalaspuffar** [comment]
Hi @sengsational 

Well, the size change is not that significant so maybe we can think of doing this change. Then again not using a support library for older phones when we add it for supporting older devices sounds fishy.

Best regards
Daniel

**Comment by sengsational** [comment]
While working on another project, I came across some documentation about support for vector graphics on old API's.  I've copied test this page: https://developer.android.com/studio/write/vector-asset-studio#apk

> Delivering an app Containing vector drawables

If you used the Support Library technique or your minimum API level is Android 5.0 (API level 21) or higher, your APK will contain the vector drawables that you added with Vector Asset Studio. These APKs will be smaller than if the vector images were converted to PNGs.

When your minimum API level includes Android 4.4 (API level 20) or lower, and you have corresponding vector drawables and raster images in your project, you have two options for delivering your APK files:

    Create one APK that includes both the vector drawables and the corresponding raster representations. This solution is the simplest to implement.
    Create separate APKs for different API levels. When you don’t include the corresponding raster images in the APK for Android 5.0 (API level 21) and higher, the APK can be much smaller in size. For more information, see Multiple APK Support.

**Comment by kalaspuffar** [comment]
Well closer to the top you had this passage 

```
If you want to use vector drawables only, you can use Android Support Library 23.2 or higher. This technique requires a change to your build.gradle file before you run Vector Asset Studio, as described in Support Library Backward Compatibility. The VectorDrawableCompat class in the Support Library allows you to support VectorDrawable in Android 2.1 (API level 7) and higher.
```

Which suggest that it should be doable without multiple APK versions. Then again we can create low res versions of the icon to use on older phones. We will save space, the icon might not be pretty but functional. And it will not weigh much for newer devices.

What do you think?

**Comment by sengsational** [comment]
I think that including a low res icon to be used on older phones sounds like an easy solution.  The problem is  how to have a single APK that uses raster on old API and vector on new API.  I need to do research to see how to do it or if it's possible.

Using VectorDrawableCompat would also require research, because my earlier conclusion was that it might not work the same for _launch_ icons (as opposed to icons within the application).

So, yeah, digging is required.

**Comment by alexhauser** [comment]
Hi @sengsational, 

did you find a viable solution for this issue yet?

Best regards, 
Alex

**Comment by sengsational** [comment]
I still need to research the options.  

As it stands, only the people running old OS's are impacted, and only impacted in that the launch icon isn't customized.

If anyone has references for using vector _launch_ icons on older OS's, please advise.

**Comment by kalaspuffar** [comment]
Hi @sengsational and @alexhauser 

I've been thinking and looked at my phones icon and realized that even the newer phones show the icon incorrectly. I guess it can be because of being an image with transparency. Google play had some issues with that to.

Maybe switching over to using pngs without transparency or perhaps even jpegs for these icons could be an option.

We don't use the svgs anywhere else in the application and we will have a bump in size when we add another background so the icons might be the least of our problem when size is concerned.

I still want to keep the list of dependencies down to lessen complexity and security risk.

Still on vacation but had some time for some thoughts :)

Best regards
Daniel

**Comment by alexhauser** [comment]
I also think we should just include the pngs at this point.

**Comment by alexhauser** [comment]
Hi @kalaspuffar and @sengsational ,

I'm in the process of creating the launcher icons (vector + legacy) using "Asset Studio":

![launcher_icons](https://user-images.githubusercontent.com/4005543/61372432-66383b00-a897-11e9-973d-670b204980e7.jpg)

My questions:
- Do we want round or square icons for the lagacy APIs?
- Should I also generate the Play Store icon or should I disable this?

Best regards,
Alex

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

All icons for the application should be generated. All store assets are located in the google_aaset folder.

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi @kalaspuffar , 

thanks for dropping by even during your vacation time! Your answers don't directly address my questions, but that's ok, I'll just go ahead and post a PR for you guys to check out. We can always change stuff if necessary.

Best regards,
Alex

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

I'm winding down after the day. Sorry if unclear.

1. Yes to legacy
2. No, already created.

The other assets needs work though, and we have an open issue for that.

Best regards
Daniel

**Comment by alexhauser** [comment]
LOL @kalaspuffar , it seems your wife has got full control over you right now. 🤣

Question one was not if we want legacy icons or not, it's clear that we do, but whether we want round or sqare icons. In other words, for API levels that only support one launcher icon, should it be round or square? But don't worry, I'll make a suggestion in a PR and we can always change it if you don't like what I've come up with.

Have a great time,
Alex

**Comment by alexhauser** [comment]
Hi @kalaspuffar, I guess this can be set to "solved", too.
