### ISSUE TITLE
Tap the status bar icon to scan QR code

### ISSUE THREAD

**Issue by sengsational** [kalaspuffar/secure-quick-reliable-login#288]
### Tap the status bar icon to scan QR code

*Short description of the feature*
Give the user the ability to tap the quickpass status bar icon to go directly to scanning.

*Use cases*
After the user has enabled quickpass and there is a sqrl icon in the upper left of their phone, this feature proposes to change the default action to go directly to scanning.  This would save them from having to hunt for the standard sqrl launch icon, launch the app that way, then click the scan button.

The current functionality to remove quickpass is something that could be offered as a floating action button on the scanning screen.

**Comment by alexhauser** [comment]
How about allowing for both actions when swiping down on the notification?

**Comment by sengsational** [comment]
When I drag down on from the top of my phone I see this:
![image](https://user-images.githubusercontent.com/15800701/56072744-ed8d8400-5d67-11e9-9ca2-b5041fbd95b6.png)
We can have the listener do whatever we want it to do.  I don't think we have the ability to do anything with a swipe listener because the Android OS is listening and if it hears a swipe, it removes the instance.

My proposal is, rather than go to the "Remove QuickPass from Memory" activity, it would go to the scan activity.  The normal process would be to swipe down, tap, scan, then the login would occur.  But by adding a floating action button on the scanning page, we could "Remove QuickPass from Memory", or just "Cancel Scan".

**Comment by alexhauser** [comment]
In the Gmail app, when you swipe down directly on the email notification in the notification drawer, you get two buttons for two different actions:

![InkedScreenshot_20190413-090211__01_LI](https://user-images.githubusercontent.com/4005543/56092450-81706480-5ebc-11e9-940a-d1717237e988.jpg)

I like the idea of having the same for the SQRL notification, with the two buttons being "Scan code" and "Clear quickpass". This way, we could do everything directly from the notification.

**Comment by kalaspuffar** [comment]
Hi @alexhauser

That was a thing I considered as well early on but as the comments in the forum pointing to this feature not being meaningful I'm considering scrapping it all together.

The reference client have no indication that quickpass is active so the Android app don't require it. I just thought it could be a nice UI feature. But if the user don't care it can cause more confusion than needed.

If we can't require the user to see the reason to protect their identity with a stronger password we don't need a feature to fall back and remove quickpass which render the notification mute and more annoying than useful.

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi Daniel, after reading your post, I fully agree with your reasoning.
Actually, as a Windows developer, this reminds me a bit of the time where every app would have a tray icon visible at all times, without any real benefit to the user.

**Comment by sengsational** [comment]
Scrapping the icon completely is one possibility, but I'd rather the icon be available so the user can quickly trigger the scanning of a QR code.  The alternative is for the user to seek-out the SQRL launch icon, which to me seems less convenient for the "camera scan QR code" use-case.  If the user was just tapping the QR code in the browser, they wouldn't need to seek-out the app, so the icon might seem to be unhelpful.

But as it stands right now there is what I consider a "bug": the user can swipe away the icon, so we have QuickPass active, but we have no icon to show it.  This could be resolved by adding `.setOngoing(true)` to the Notification (means that the user can't swipe it away).

While I think putting several actions in the notification would give the user the most flexibility, I'm thinking there might "never" be a reason to remove QuickPass from memory.  At least that's the thinking of respected members on the sqrl forum.  

All that said, I do agree that some people will not want the icon showing all the time.  That can be controlled in user preferences (settings), and the "display icon setting" could be shown by default after a new install, and instructions for going into settings to turn it off could be part of the onboarding.

**Comment by kalaspuffar** [comment]
Comment from a user which shows the strangeness of the feature and another reason for removal.

"Cool app. I have gotten stuck at the page titled "clear quick pass quickpass removed" . I think that page needs a return or Ok button. When I press the back button I just return to my Android home screen. The notification about sqrl Id in memory also does not indicate that clicking it will take ID out of memory. It was also not clear how to use fingerprints for access from the interface."

**Comment by sengsational** [comment]
I have been convinced that initiating a QR code scan from notification icon is not a good idea; there are other ways to initiate a QR code scan, so using the notification icon for that purpose probably isn't is a good idea.
