### ISSUE TITLE
Constraint layout error for login popup

### ISSUE THREAD

**Issue by kalaspuffar** [kalaspuffar/secure-quick-reliable-login#291]
Seems like we have a bug in the constraint layout of the login popup.

This issue is reported by Chauncy at the forums.

**Comment by kalaspuffar** [comment]
![image](https://user-images.githubusercontent.com/1424084/56097972-607b3400-5efb-11e9-9acf-7c7594aff13f.png)

**Comment by sengsational** [comment]
Can this be closed, or does it stay open until a new release is posted?
