### ISSUE TITLE
Go straight to scan if QuickPass active

### ISSUE THREAD

**Issue by sengsational** [kalaspuffar/secure-quick-reliable-login#294]
### Feature discussion

*Short description of the feature*
If QuickPass active, start the scan intent rather than main screen.

*Use cases*

When QuickPass is active and if the user wishes to authenticate on a PC web browser, there is no need to visit the standard startup activity. My thinking is that if the user has QP active, it means the chances they need to do something besides scan are almost nil. In other words, they've got everything configured and they just want to log in somewhere. Of course they can back out of scanning on the rare case that they need to do some "identity housekeeping", but for someone who's clicking on the SQRL client button on their phone as a normal, routine user, it's almost certain they intend to scan.

The case against this feature is for users that typically don't use the scanning, but instead click QR codes in the browser. For them, if they open the client directly, they will almost certainly be interested in doing "identity housekeeping". But I expect that housekeeping tasks will be very rare once the app is set up and being used on a routine basis, so the user who has housekeeping tasks can back out of scanning and go to the settings or advanced activity.

**Comment by alexhauser** [comment]
I can see the use case for this, but I'm also hesitant because I think it can be confusing if we launch the camera right away without the user explicitly wanting to initiate a scan.

So for me, this should be implemented as an optional feature that can be turned on in the (yet nonexistent) "application-wide" settings.

**Comment by sengsational** [comment]
I'm thinking that you're right...launching the app normally should always do the same thing.  I've got an alternate idea that is a better way to manage the quick scan.  Since the alternate idea doesn't fit under this subject, I'll close this one.
