### ISSUE TITLE
Make Alt-ID work as it does in the Windows client

### ISSUE THREAD

**Issue by sengsational** [kalaspuffar/secure-quick-reliable-login#295]
### Feature request.

*Short description of the feature*
Give the user guidance if they are considering logging into a web site with an "Alt-ID" from within the login flow.

*Use cases*
On the various login activities, the user should have the ability to make an informed decision about whether creating an "Alt-ID" is appropriate, similar to the Windows client.

![altid](https://user-images.githubusercontent.com/15800701/56616845-61435280-65ec-11e9-8a3b-ca23332b3b8a.jpg)

**Comment by alexhauser** [comment]
I guess this one is obsolete, now that we have a different Alt-ID flow incoming.

**Comment by sengsational** [comment]
Yes, this is obsolete.  Closing it.
