### ISSUE TITLE
Switching Identity on Login Should Wipe QuickPass Prompt

### ISSUE THREAD

**Issue by sengsational** [kalaspuffar/secure-quick-reliable-login#296]
### Issue or error solving.

*Short description of the issue*
Using "Current Identity" drop-down on the login screen does not wipe the QuickPass prompt.

*Expected behavior*
If an alternative identity is select in the drop-down, the suggestion text should say "Password"

*Actual behavior*
If an alternative identity is select in the drop-down, the suggestion text  "Password (First [n] characters)"

*Steps to reproduce*

1. Client with more than one identity
2. Authenticate such that QuickPass is active.
3. Start authentication process again, getting to  domain validation login screen.
4. Use the drop-down to select another identity
5. "Password (First 4 characters)" is shown (unexpected). 

*Discussion*
Note that the QuickPass state seems to be operating properly.  In other words, although the prompt says that the first [n] characters will be sufficient, the entire SQRL master password is required, so this is just a UI related bug, not a SQRL QuickPass "data state" bug.

**Comment by alexhauser** [comment]
Hi @kalaspuffar,

this seems to have been fixed by your referenced PR 305, at least I've just successfully tested it. 

Can this be closed, or are there any other issues?

Best regards, 
Alex
