### ISSUE TITLE
Consolidate rescue code input layout

### ISSUE THREAD

**Issue by alexhauser** [kalaspuffar/secure-quick-reliable-login#298]
### Optimization suggestion

This applies to this particular part of our UI:

![rescue_code_input](https://user-images.githubusercontent.com/4005543/56957203-ab758800-6b46-11e9-821f-a2a3de5a0f4c.JPG)

I noticed that we have the same (or at least very similar) layout code for entering the rescue code 
duplicated on all of these activities:
```
activity_enable_account.xml
activity_rekey_verify.xml
activity_remove_account.xml
activity_rescuecode_show.xml
activity_rescuecode_enter.xml
activity_reset_password.xml
```
Does this serve any special purpose or are there important differences between the different layouts that I didn't notice on my quick review? If no, should we consolidate this to a separate .xml layout file which we can then include in all of these activities?

This would make the layout code much more maintainable imho.

Thanks in advance for any input or suggestions!

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

Not to my knowledge. Been a while since I wrote that code thought :)

Consolidation is good. Most of the code have been written in a ad-hoc manor knowing I had to change it later. This part might have stabilized enough to break out though.

Best regards
Daniel

**Comment by alexhauser** [comment]
Thanks for sharing the background info, @kalaspuffar ! I'm starting to work on this.

Best regards,
Alex
