### ISSUE TITLE
Strength meter in dark mode.

### ISSUE THREAD

**Issue by kalaspuffar** [kalaspuffar/secure-quick-reliable-login#306]
### Issue or error solving.

Strength meter error message is unreadable in dark mode.
![issue1](https://user-images.githubusercontent.com/1424084/57105750-de2ca580-6d2b-11e9-90f2-54ad3a552a88.png)

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

Can you verify dark mode functionallity.

You should be able to set it with 
AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES);

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi @kalaspuffar ,

thanks for pointing this out. I've actually noticed this myself today and have already prepared a fix in my local repository. Do you agree that we should use a fixed font color on those components that suits all three states? Or is there a better way to solve this? 

Thanks and best regards,
Alex

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

Not really. Think of dark mode as a view used by light sensitive people or when using the app in the dark. So finding colors and fonts that work and follow the overall asterisks of the application is more important.

Then again we might get some more input about flows and color scheme when the design team have looked at the application further.

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi @kalaspuffar ,

the dark mode glitch should be fixed with the last PR, however, I've noticed another display bug: When translations are long, the character class indicators get pushed off the screen to the right. Guess I'll open a new issue for this tomorrow.

Good night, everyone ;)
Alex
