### ISSUE TITLE
Improve user experience of MainActivity

### ISSUE THREAD

**Issue by alexhauser** [kalaspuffar/secure-quick-reliable-login#317]
### Enhancement: Improve user experience

I am aware that we are awaiting input from UI/UX experts in the forums at the moment, but as there hasn't been any real progress over the last few weeks, I thought I would ask if we shouldn't at least improve what we've got so far.

To me, the most "frightening" part of the UI at the moment is what I like to think of as the *"button graveyard"*, which is our `MainActivity`, aka *"Advanced operations"*. At the moment, we have **11 buttons** stacked up vertically, with button topics mixed up wildly, which I think everyone will agree, is not the best user experience one can think of.

One currently still open PR will already consolidate the import options into its own activity which helps a little. But there is much more room for improvement here I think.

Here are some suggestions for quickly implementable fixes, which, while not providing a complete solution to the overall UX problem, would at least mitigate it a little:

- [x] **Remove the button `Use Identity`.** 
Am I right in assuming that this a remnant from the time before `SimplifiedActivity`? To me, it is not even immediately clear what "use identity" even means, and I think we should keep the operational aspects of the app separated from the "identity management" aspect. I think the main action in `SimplifiedActivity` should be the only way of invoking a qr scan.
- [x] **Move `Settings` into the main overflow menu**
We could even think about showing it as an icon in the action bar. But I think it makes sense moving it one level "higher", away from the other purely "identity management" related options.
- [x] **Move `Change Password`, `Reset Password` and `Rekey` into its own sub activity.**
This could then be called `PasswordOptions` or something similar.
- [x] **Consolidate import options** 
Already implemented in pending PR *"File import feature and import UI consolidation"*
- [x] **Rename `MainActivity`** 

This would leave us with "only" the following options in `MainActivity`:

 - Create New Identity
 - Remove Identity
 - Rename Identity
 - Export Identity
 - Import Identity
 - Password/Rekey Options

I also think it would then be appropriate to rename `MainActivity` to `IdentityManagementActivity` and call the correspoding overflow menu item `Identity Management` instead of `Advanced operations`. 

@kalaspuffar ,
I would totally understand if you'd rather wait for the UI/UX experts to finally present something, but this is bugging me already for quite some time and I wanted to at least get a discussion going.

Looking foward to your feedback, guys!

Best regards,
Alex

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

The first easy issue is the name change. And I agree we the names you suggested are better.

Settings are saved on the identity and are identity specific so moving them away can have implications. 
Changing the structure to have "password related" things in one submenu is an option but there are many such options and after thinking about it for a while I gave up and asked for help. 

The graveyard is an annoying solution but it will prompt someone to change it in the future. And I have many solutions but none of them are good :)

Removing "Use Identity" is an option. I just wanted it there for easy access if you switch identity often but that use case might not be valid.

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi @kalaspuffar , 

thanks for the feedback. Shall I repare a PR for only the name change then or do we leave the whole thing until we've got word from the UI/UX experts?

Best regards,
Alex

**Comment by sengsational** [comment]
I'd vote for putting all the changes in now because 1) it's obvious to me that it's a move in the right direction, and 2) it's not clear that our UI people will deliver.

One idea I had was to have a standard, nice looking "settings" page which allows the the app-level things (Android app stuff), and then a "SQRL settings" page which contains the stuff that's in the encrypted blob.  This would allow the user to customize the app without typing the password.

I think Steve's Windows client can probably be used to set the "speed bumps" to keep people generally out of the rekeying and stuff like that; I think he's got the user running through typing the rescue code in some cases, not because it's needed, but because it's something people almost never need to be messing with.

**Comment by kalaspuffar** [comment]
Hi @sengsational and @alexhauser 

I think we can do the name change for sure as it will improve the code readablility.

Removing the Use Identity could also be nice to remove confusion.

Consolidating buttons could be good but I would like to see a couple of options so we can find the logically simplest solution. 

So if you never used the app before where would you expect to find this option?

Best regards
Daniel

**Comment by alexhauser** [comment]
Hey folks,

the name changes as well as the removal of `Use identity` is dealt with in the PR referenced above.

I'm open for other suggestions for the further improvement of the newly renamed `IdentityManagementActivity` (formerly `MainActivity`).

My suggestion for consolidating password related options still stand as described in the initial issue description:
- **Move `Change Password`, `Reset Password` and `Rekey` into its own sub activity.**
This could then be called `PasswordOptions` or something similar.

As for the settings topic, I somewhat like @sengsational's idea to have application-wide as well as identity-specific settings, but have no clear picture of how exactly it should be implemented yet. Also, do we even have/need an application-wide setting yet? For me, this one still needs some more thought.

Any ideas for improvement are highly welcome!

Best regards,
Alex

**Comment by alexhauser** [comment]
Hi @kalaspuffar and @sengsational ,

What do you think of something like this ...

<img src="https://user-images.githubusercontent.com/4005543/58470871-e74e3e00-8142-11e9-9ccf-3d4189115316.JPG" width="400">


... where the options related to the selected identity are available in a popup menu:

<img src="https://user-images.githubusercontent.com/4005543/58470967-2086ae00-8143-11e9-97ed-5c8e009e3259.JPG" width="400">

Looking forward to your feedback,
Alex

**Comment by sengsational** [comment]
Yes, That's a great step in the right direction.

**Comment by alexhauser** [comment]
Thannks @sesam and @sengsational for the positive feedback.
@kalaspuffar , should I prepare a PR for this or do you have any objections?

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

I haven't been able to find a better solution :)

Best regards
Daniel
