### ISSUE TITLE
Wrong password error message covered by logon popup

### ISSUE THREAD

**Issue by sengsational** [kalaspuffar/secure-quick-reliable-login#325]
*Short description of the issue*
Message `showErrorMessage(R.string.decrypt_identity_fail);` is covered by login popup.

*Expected behavior*
The login popup does not cover the error.

*Actual behavior*
The login popup covers the error.

*Steps to reproduce*
Scan a web login QR code.
Type the wrong password.
The login popup shows.
Dismiss the login popup without using it.
Now you can see the error message.

*Discussion*
I thought we had fixed this at one time, didn't we?

**Comment by kalaspuffar** [comment]
Also thought we solved it. Maybe some code has reverted during all refactoring.

**Comment by alexhauser** [comment]
This one can be closed as well, right?
