### ISSUE TITLE
"Missing argument" error on biometric login

### ISSUE THREAD

**Issue by alexhauser** [kalaspuffar/secure-quick-reliable-login#329]
### Issue or error solving.

The error message "Missing argument" sometimes shows up on biometric login.

*Expected behavior*
Successful login

*Actual behavior*
Error message shows up

*Steps to reproduce*

- Clear the app from memory to ensure a clean starting point
- On the device, visit https://www.grc.com/sqrl/demo.htm? and tap `Log in with SQRL`
- The app's login prompt appears. Enter the correct password. You will be sucessfully logged it.
- Log out of the website
- Start the SQRL app using the launcher icon and edit the identity's settings (e.g. change idle timeout) and confirm by entering the password.
- Change back to https://www.grc.com/sqrl/demo.htm? and tap `Log in with SQRL` again
- Since QuickPass is now active, the biometric login prompt appears
- Use fingerprint reader 

At this point, the error message shoud appear.

<img src="https://user-images.githubusercontent.com/4005543/58721381-2c899e80-83d5-11e9-86e7-821ed9348c4b.jpg" width="400">

**Comment by sengsational** [comment]
Good catch.  Something like this has been a problem since the first time I used the app many months ago; I noticed that establishing quickpass from settings vs establishing quickpass from a website login were not equivalent somehow.  I did a lot of noodling on it, but never found the smoking gun.
