### ISSUE TITLE
Monospace / Large domain name

### ISSUE THREAD

**Issue by sengsational** [kalaspuffar/secure-quick-reliable-login#331]
### Feature request.

Make domain name monospace and as big possible

*Use cases*
We ask SQRL users to validate the domain so they don't go to a spoofed site.  This will make it easier to detected ambiguous letters in the domain name.

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

The big reason is that the normal login flow is made in a way that you usually have an identity selected, and when you scan the QR Code, you will log in with that identity.

The URL flow is different as it's disconnected with the rest of the application, and you don't have any way to change the identity in that flow. So we added the select box there.

Another reason to now have too many details in the standard login window is that it's a popup and space is limited. Once upon a time, most of the application was popup windows. Now, this is probably one of the few left :)

Now you have some reasons and some history. I'm not saying that it has to be this way, but I want to explain why it is as is.

Best regards
Daniel

**Comment by alexhauser** [comment]
Thanks for the feedback @kalaspuffar , I appreciate you taking the time to share some background information and giving insights into the "early days". 👍 

I can totally understand how such a project almost inevitably develops its natural bloat and wrinkles over time, especially when you just want to get stuff working as fast as possible in the beginning. You're always wiser one or two years into the project, that's just how it goes. I've seen it in my own projects time after time.

But as you say, we are free not to leave it at that.

Thinking about all this, I'd really like to try to code a single "identity switcher" widget that can be included wherever it's needed. And I'd like to consolidate the login ui code after that's done. I think it would be worth the effort in terms of maintainability. 

For now, if you guys find my solution for the domain name display acceptable, I'd like to prepare a PR to get this in and open a new issue for the consolidation stuff.

So any feedback on the domain display would be appreciated. Thanks!

Best regards,
Alex

**Comment by sengsational** [comment]
Alex, it looks like we had the same general idea for the big monospace font for the domain.  It looks like your examples shows two sizes.  The idea I had (which was just an idea, and unlike you, I didn't work on it), was to use some width calculations to maximize the size without wrapping (up to a point).  And if the size was "too small" without wrapping, repeat the maximization, this time with rows = 2 instead of 1.  That might not be real clear, but the idea is to use the entire width of the screen, no matter how long the domain is.  That's a "hard assignment", but I read somewhere in the distant past that you can ask Android how wide the screen is, then do math on your textview at different font sizes.  Again, it was just an idea as I was nodding off to sleep the other night.  Probably "too complicated", but then again, I'm working on this project to learn more about what's possible :)

**Comment by kalaspuffar** [comment]
Hi @sengsational and @alexhauser 

First of, creating a dynamic font size should not be that complicated, but I don't think it's necessary. The second example is good, I think. Even if it wraps or not, it has a larger text that stands out without being extreme. 

If you have a hard time to read it you will increase the font size, and that can bring the text up to a really large size, and you want that change to reflect well in the UI. If you make the font dynamic people that rely on the larger text will not get as a distinct size change.

I like that we keep the primary color as text color and I hope its contrast is large enough for this use. But as we increase the size so should the legibility also increase even if we decrease contrast.

Good work Alex.

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi @sengsational and @kalaspuffar ,

at first I also thought I would have to do the font sizing/measuring myself, but it turned out that Android actually does exactly what @sengsational describes "for free" when using  `app:autoSizeTextType="uniform"` on a `android.support.v7.widget.AppCompatTextView`. 

So my solution is in fact already providing dynamic font size and will make "normal length" domain names use the whole screen width:

<img src="https://user-images.githubusercontent.com/4005543/58856974-4b718480-86a4-11e9-96ff-49e905becac3.JPG" width="300">


However, ALWAYS using the whole width turned out to be suboptimal, because it would have made short domains rediculously large, which looked quite silly and would use way too much screen real estate.

So I am using `app:autoSizeMaxTextSize="36sp"` as well as `app:autoSizeMinTextSize="20sp"` to keep the font size within certain bounds. 

We can of course always tweak these values later on if we find instances where it doesn't work out well.

Best regards,
Alex

**Comment by sengsational** [comment]
As to the " rediculously large", I figured that would be a problem and and that's why I said "up to a point".  

Great news that Android does the character width math for us!  Looks great.  A big improvement into getting the domain more prominent.

**Comment by alexhauser** [comment]
I guess this one can be closed.

**Comment by sengsational** [comment]
As a point of process management, do these close after merge or close after release?  If it's the latter, we might consider a label "close on next release" or something like that.  My collaborative experience was limited to corporate stuff in the past, so not sure how this is "supposed" to work.

**Comment by alexhauser** [comment]
Good question, @sengsational. 
I guess this is something for @kalaspuffar to decide.

**Comment by kalaspuffar** [comment]
Hi @sengsational and @alexhauser 

I've up to this point added the label Solved until we have released and then close the Solved issues on release. Does this sound good or should I change the name of the label?

Best regards
Daniel

**Comment by alexhauser** [comment]
Sounds good to me! :-)

**Comment by sengsational** [comment]
I think "Solved" is good.  Except this one ended up (as I'm looking at it now) with only 'enhancement'.
