### ISSUE TITLE
Separate/Segregate Login and Web Interaction

### ISSUE THREAD

**Issue by sengsational** [kalaspuffar/secure-quick-reliable-login#333]
### Separate/Segregate Login and Web Interaction as tasks

*Short description*
Currently the code has login and web interaction together in a PopupWindow.  This work item is to separate the various activities into stand-alone modules.

*Use cases*
In the early days of the application, where there were fewer things going on in the code, it made sense to have these activities tied together.  Now that we have more possibilities, it makes sense to have stand-alone activities that can be assembled together as needed.  For instance, with the "Engage QuickPass" function, only login is needed, no web interaction.  Login only is needed when working with identities.  Given the functionality is the same, best practices suggest that the code be included exactly once, and re-used as needed.  This suggests that Login be a separate activity.  Since it takes too long to run on the main thread, it should probably be in an AsynchTask.  The same is true for any process that interacts across the network.  These "interactor" tasks can be started and then they can call back with their results.  Although these things can be done by managing threads directly , as is the case now, it's probably more robust to leverage as much of the Android infrastructure as possible to accomplish these goals.

**Comment by alexhauser** [comment]
Hi @sengsational ,

what's your feeling regarding this issue item after two months of updates and lots of consolidation? Some things mentioned here are clearly obsolete by now, while others might still apply to the current code base.

Is this something we should keep open, or - should you still feel a need for change - would you prefer opening a new, updated issue that takes the latest developments into account?

Thanks and best regards,
Alex

**Comment by sengsational** [comment]
I agree that this issue can be closed, given the application has moved on considerably since the original issue was drafted.  I still think that the more Android-like way to accomplish long-running activities is to utilize async task and, at the time, we were getting crashes that could have been related to manually created threads and CommunicationFlowHandler.  But as long as it looks like it's doing the job, no need to concern ourselves.
