### ISSUE TITLE
Identity selection enhancement

### ISSUE THREAD

**Issue by alexhauser** [kalaspuffar/secure-quick-reliable-login#337]
*Current situation*

At the moment, identity selection UI and functionality is spread out between multiple places. Also, it is dependent on functionality provided by `LoginBaseActivity`, which is suboptimal for places that would benefit from being able to change the current identity but are not related to login (like identity settings for example).

*Planned enhancement*

The aim is to consolidate and simplify identity selection by introducing a single, space-economic UI fragagment `fragment_identity_selector.xml` and its corresponding `IdentitySelector` class which can be used in all the places troughout the app that need the ability to change identities.

Here is a suggestion on how the "widget" could look like:

<img src="https://user-images.githubusercontent.com/4005543/59029489-b36bca80-885e-11e9-81a2-ac6bfbc46961.JPG" width="400">

*Features of the `IdentitySelector` class/ui* 
- Auto-adjusts based on number of identities
(read-only if only one identity exists, otherwise clickable to select identity)
- Changing identities can be disabled (force read-only)
(this makes the widget usable also in places where we just want to display the currently active identity without giving the ability to change it)
- Supports registering a listener which is being fired on identity change to enable custom behaviour

I would also like to replace the spinner (which need a lot of messy glue code) with a simple dialog for choosing identities, which only takes a few lines of code to implement using `AlertDialog.Builder.setSingleChoiceItems()`:

<img src="https://user-images.githubusercontent.com/4005543/59029717-4f95d180-885f-11e9-92d8-311654dec758.JPG" width="400">

I have all the code for this ready, but would like to hear your feedback first, @kalaspuffar , @sengsational and @sesam , before posting the PR.

**Comment by sengsational** [comment]
Getting this stuff out of `LoginBaseActivity` is a good idea.

While I consider handling multiple identities smoothly an essential ingredient, I'd like to see the app operate as if there was no multiple identity functionality _if there is only a single identity defined._  My thinking goes like this..."most people" won't have multiple identities (at least according to Steve's master plan anyway).   So if there's something people see that suggests they could have multiple identities, it plants the seed that maybe they "need" more and one. Then we'd be driving people in what's arguably the wrong direction.

I think it shouldn't be too hard to just present the identity switcher if there's more than one identity?

**Comment by alexhauser** [comment]
> I'd like to see the app operate as if there was no multiple identity functionality if there is only a single identity defined.

I fully agree.

> I think it shouldn't be too hard to just present the identity switcher if there's more than one identity?

Right, this is trivial. I'll add a switch, something like `autoHideOnSingleIdentity`.

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

I like the new design. Never really liked the Spinner and before I understood it I really hated it. Rewrote it recently when I understood the underlying design. Still, don't like it but it's better. So if you want to improve it by removing it then by all means do :)

I think Spinners is something that is web-native but not really used on Android.

Best regards
Daniel
