### ISSUE TITLE
Problem with strings.xml in master

### ISSUE THREAD

**Issue by sengsational** [kalaspuffar/secure-quick-reliable-login#343]
### Extra escape in strings.xml

*Short description of the issue*
In `idle_timeout_guidance` string definition, the text `..after which you\\'ll have to...` appears and it causing a compile error.  Note that `\\'` should be `\'`

![escapes](https://user-images.githubusercontent.com/15800701/59154584-02725500-8a43-11e9-89cc-4e079560042a.jpg)

**Comment by kalaspuffar** [comment]
Thank you for pointing this out! :)

I found it when I analyzed the release before pushing it.
