### ISSUE TITLE
Improve "reset password" step on import without password

### ISSUE THREAD

**Issue by alexhauser** [kalaspuffar/secure-quick-reliable-login#348]
### Enhancement

From https://sqrl.grc.com/threads/import-via-qr-fail.716/ :
> The Android app could be made a little less confusing by using a different term than "Reset Password" when importing an identity without its associated password. Maybe use the phrase "New Password For This Device Only" or a basic explanation of what is actually happening.

**Comment by sesam** [comment]
Yes, this is important. SQRLs "passwords" are very different from what users are used to. And probably we should recommend passphrases rather than words. On mobile, you can slide-write words, making it harder to shoulder surf the pass.
