### ISSUE TITLE
Consider removing file intent filter

### ISSUE THREAD

**Issue by alexhauser** [kalaspuffar/secure-quick-reliable-login#351]
### Issue or error solving.

The file intent filter is causing issues for people, see https://sqrl.grc.com/threads/sqrl-pop-up-when-accessing-google-drive-files-when-offline.717/

Since file import is already possible by picking a file from within the app, this functionality is not strictly necessary and probably not worth the troubles.

@kalaspuffar , with your consent, I suggest to remove this functionality, at least until Google provides a robust way to filter files by file extension.

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

I say we remove it as it hurts someone's experience and it does not add enough benefit.

Best regards
Daniel
