### ISSUE TITLE
Disabling account creates bad state

### ISSUE THREAD

**Issue by kalaspuffar** [kalaspuffar/secure-quick-reliable-login#371]
### Issue or error solving.

*Short description of the issue*

After unlocking the account, I tried to log in again, but after going through the login in the app, it just directed me back to the website, which - again - apparently just reloaded the login page but never logged me in. To fix this, I had to start the app from the launch icon (since the login activity does not appear in the recent apps anymore), and then clear it from memory by swiping it away in the recent apps. Only after that, the login would start working again.

*Expected behavior*

Was able to log in

*Actual behavior*

Could not log in until app was reset.

*Steps to reproduce*

1. Disable account
2. Enable account
2. Try to login again

**Comment by kalaspuffar** [comment]
QuickPass issue?

**Comment by alexhauser** [comment]
Could be. It always happend with QuickPass engaged.

**Comment by alexhauser** [comment]
Hi @kalaspuffar ,

this is still an issue even after PR #382. I also don't think it's QuickPass-realated any more, since all my mitigation in that direction were fruitless. It's probably something rather low level (storage or comm), could you please look into this sometime when you're back from your vacation and find some time to spare?

Best regards,
Alex

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

I tried this issue with the new version and could not recreate it so it seems the new flow solved my problems. I'll close this.

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi @kalaspuffar ,

I've just verified that it indeed works as expected now! Thanks!

Best regards,
Alex

**Comment by mozzworld** [comment]
@kalaspuffar, @alexhauser,
After the diable, enable sequence, I had the same experience (could not login) until I cleared the browser cache. I was using version 1.5.1 downloaded from F-Droid to login to sqrl.grc.com - @mozz sqrl.grc.com

**Comment by kalaspuffar** [comment]
Hi @mozzworld 

Seems to be an issue with the website if a clearing of browser cache can solve the issue.

Best regards
Daniel

**Comment by mozzworld** [comment]
Hi. @kalaspuffar,

Now that I know how to work around, it's okay. As things are still in progress, I am hopeful such issues will be taken care of in due course.

With regards,

Mozz
