### ISSUE TITLE
Check if QR code import still works

### ISSUE THREAD

**Issue by alexhauser** [kalaspuffar/secure-quick-reliable-login#372]
See https://sqrl.grc.com/threads/import-via-qr-fail.716/post-5988

> On the Android APP, I select import identity, scan identity QR Code.
This brings up the textual part of my identity and it also requests a password. Entering in my master identity password does not work.

**Comment by alexhauser** [comment]
Just checked with two different identities, with password and without password, both worked fine, just as expected. Can anyone confirm?

**Comment by kalaspuffar** [comment]
I've tested a large identity with and without a password. Both still work.

**Comment by alexhauser** [comment]
Thanks for the confirmation. I will close this issue once the forum poster confirms that the problem is on his side.

**Comment by alexhauser** [comment]
Since there is no further freedback from the forum and our testing showed that the feature works just fine, I'll close this.
