### ISSUE TITLE
Enhanced dark mode / night mode

### ISSUE THREAD

**Issue by alexhauser** [kalaspuffar/secure-quick-reliable-login#376]
### Enhancement.

I'd like to improve how `SimplifiedActivity` looks in dark mode. Right now, it's still much too bright, the colored background image and the light accent color are huring the eyes in the darkness. This is the current status quo:

<img src="https://user-images.githubusercontent.com/4005543/60622558-ec0cae80-9de0-11e9-8b17-582ce9908733.JPG" width="300">

So I've toyed around with different backgrounds and colors, and this is what I ended up with:

<img src="https://user-images.githubusercontent.com/4005543/60622685-2e35f000-9de1-11e9-89a5-4cd0b7e81dd2.JPG" width="300">

What do you guys think? Any input is highly appreciated!

**Comment by alexhauser** [comment]
Being on a different system now, it looks almost too dark. 
Any thoughts?

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

How about using s different image, make keeping the button .

If you either have a darker button on lighter background or a lighter background with a darker button for more contrast.

I thought a image of the milky way could give the same feeling of going somewhere.

https://commons.m.wikimedia.org/wiki/File:Milky_Way_Galaxy.jpg

What do you think?

Best regards
Daniel

**Comment by alexhauser** [comment]
Looks interesting, I'll give it a try!

**Comment by alexhauser** [comment]
Even though it looks a little esoteric, I still kinda like it:

<img src="https://user-images.githubusercontent.com/4005543/60677623-5164ac00-9e82-11e9-8783-3c4cc6bda71e.JPG" width="300">

I think the balance of dark and light is just about right there. 
What do you think?

**Comment by kalaspuffar** [comment]
I like it but I think there is one color too much. Either the title goes to purple or the button text goes white.

I like the color though so maybe the title would be the reasonable change. I would like to remove the title as well. I like a large area with a button and the title is not required. We need the menu for access but maybe we can use a different component for that.

Floating action button with multi buttons on click perhaps?

**Comment by alexhauser** [comment]
I'll try a few things and report back.

**Comment by alexhauser** [comment]
Hi @kalaspuffar ,

I've done some experiementing with a "fullscreen" layout implementing your suggestions: 

<img src="https://user-images.githubusercontent.com/4005543/60767203-9cfe9c00-a0b4-11e9-8c08-d2bcf5eba5d7.jpg" width="300">

While I'm not hating it, something about it rubs me the wrong way. Maybe it is the non-standard (and discouraged) use of the FloatingActionButton, or that now it's not clear anymore what app it even is that you're looking at, I don't know. 

What's your take on this?

Cheers, Alex

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

I've been thinking about this for a few days now. And I say we keep the title bar. I think the design is a real upgrade so removing the top bar and introducing strange floating elements don't add that much to the design.

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi @kalaspuffar,

thanks, glad we're on the same page here.

I'll still look into the title bar color suggestion and then post a PR if everything is ready.

Best regards,
Alex

**Comment by alexhauser** [comment]
Hi @kalaspuffar, 

just wanted to let you know that I'll wait with posting a PR for this until we know what happens to PR #382, since there would definitely be merge conflicts between the two.

And since there is no real rush with this, I think it might be the better approach.

Best regards,
Alex

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

Looking forward to this one now that we have handled the earlier merge request. This can be a really interesting improvement :)

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi @kalaspuffar,

I'll get back to wrapping this one up asap.

We still need to discuss one thing though, which I will get back to you about as soon as my daughter feels like loosening her grip on my dev notebook that she is currently abusing to play Minecraft on. 😆

Best regards,
Alex
