### ISSUE TITLE
Alt-ID is not using QuickPass

### ISSUE THREAD

**Issue by alexhauser** [kalaspuffar/secure-quick-reliable-login#379]
### Feature request.

Currently, when logging in to a site using the Alt-ID feature, we always ask for the full password, even if QuickPass is active. I guess we should fix this.

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

Yes we can. I think the more pressing matter though is getting the disable, enable and remove to use the ALT-ID account.

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi @kalaspuffar ,

you're absolutely right, this didn't even occur to me.
But I think I might have a good idea for how we could elegantly solve all of this. I'll come up with a suggestion.

Best regards,
Alex

**Comment by alexhauser** [comment]
Here is my suggestion for solving the alt-id  issues discussed above:

In the login screen, we remove the "options" button and add an (initially collapsed) area called "advanced functions" or similar:

<img src="https://user-images.githubusercontent.com/4005543/60894109-5e0e4900-a262-11e9-9e8a-14c98057a3b7.JPG" width="300">

On expanding the advanced funtions, we can enter an alt-id and also choose between the different account options (and get help using the info icons):

<img src="https://user-images.githubusercontent.com/4005543/60894155-74b4a000-a262-11e9-905f-e223a65cd7e9.JPG" width="300">

For the account options that need the resuce code, we just show an "enter rescue code" popup once the user clicks the login button (which will be dynamically labelled according to the chosen function of course).

This would provide everything in one nice login flow and enables providing alt-id functionality for account options, all without needing to jump into different activities. 

And, we can get rid of 5 activities using this approach!

@kalaspuffar , @sengsational and @sesam ,
what do you guys think?

**Comment by sesam** [comment]
Looks user friendly! How does the Altwrnative identity oart work? Free text input? Some autocomplete? I'm basically a tiny bit confused around the thin line with gray text Alternative identity.

**Comment by alexhauser** [comment]
Hi @sesam, it's just a standard `TextEdit` field for free text input, since the alternative id can be anything you like.

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

Concept, awesome. The design which might not be my expertize but the gray feel a bit "heavy" so choosing a lighter shade could be good.

In the dark design, a light border would do the same effect.

Best regards
Daniel

**Comment by sengsational** [comment]
Looks like some very good thinking there, Alex; I like it.

One thing, just to avoid a possible problem...if it's not in a scroll view, the login could become inaccessible when expanding the advanced functions, depending on the screen dimensions.

**Comment by alexhauser** [comment]
Thanks for the positive feedback, guys!

> the gray feel a bit "heavy" so choosing a lighter shade could be good.
I agree.

> In the dark design, a light border would do the same effect. 
Exactly what I was thinking!


> One thing, just to avoid a possible problem...if it's not in a scroll view, the login could become inaccessible when expanding the advanced functions, depending on the screen dimensions.
It already is!

**Comment by alexhauser** [comment]
So I'll then go ahead and start implementing it...

**Comment by alexhauser** [comment]
Hi @kalaspuffar,

is it possible that your last low level changes broke the "disable account" feature?

I am working on moving the account options into the main login flow and the "disable account" was constantly crashing on me with a `SIGABRT (signal SIGABRT)`. It was driving me nuts, since I couldn't find anything that I could have broken. When I finally switched to the master branch to check what's wrong, I found out that it crashes there as well.

The crash happens somewhere in the native code of libsodium, I think the reason is that it somehow wrongly expects a server unlock key that happens to be `NULL` at this time:

```
JNI DETECTED ERROR IN APPLICATION: jarray was NULL
in call to GetByteArrayElements
from int org.libsodium.jni.SodiumJNI.crypto_scalarmult(byte[], byte[], byte[])
```
...
```
at org.libsodium.jni.SodiumJNI.crypto_scalarmult(Native method)
at org.libsodium.jni.Sodium.crypto_scalarmult(Sodium.java:105)
at org.ea.sqrl.processors.SQRLStorage.getUnlockRequestSigningKey(SQRLStorage.java:1404)
at org.ea.sqrl.processors.CommunicationHandler.createPostParams(CommunicationHandler.java:314)
at org.ea.sqrl.processors.CommunicationFlowHandler.postDisableAccount(CommunicationFlowHandler.java:354)
at org.ea.sqrl.processors.CommunicationFlowHandler.runAction(CommunicationFlowHandler.java:235)
at org.ea.sqrl.processors.CommunicationFlowHandler.handleNextAction(CommunicationFlowHandler.java:157)
at org.ea.sqrl.processors.-$$Lambda$jgy8rto4a1WS69ckGfOa0kg109k.run(lambda:-1)
at java.lang.Thread.run(Thread.java:764)
```

Can you please have a look at this? Thanks!

Best regards,
Alex

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

Sadly my vacation will start for real now so during a week I'll be unable to look into this. Maybe I'll have some time tomorrow morning but that is maybe not enough time :(

But I'll look into it ASAP.

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi @kalaspuffar,

no worries, I can wait!

Best regards,
Alex

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

I've added a hasServerUnlockKey function that will check if the server has sent a suk before signing the message. Hopefully, this will remove the issue you're seeing. I've not been able to reproduce the problem but if it happens the code I added should prevent it :)

Best regards
Daniel

**Comment by alexhauser** [comment]
Thanks for the "last minute" work, @kalaspuffar, it's now working again in master! Great job!
Have a great vacation!
