### ISSUE TITLE
Modernize LanguageActivity

### ISSUE THREAD

**Issue by alexhauser** [kalaspuffar/secure-quick-reliable-login#384]
### Enhancement:

Modernize the look-and-feel of `LanguageActivity`.

**Proposed Changes:**
- Change the dated 3d raster images to flat vector graphics. Also, change the color of the selected item's image to use `@color/colorAccent` instead of the unrelated yellow/gold.
- Make "more_indicator" a little smaller
- Add margins to the `RecyclerView` so that its items don't stick too much to the edges 
- Bolden the currently selected language's text

This is the current state of our `LanguageActivity`:

<img src="https://user-images.githubusercontent.com/4005543/61443863-9c82c280-a94a-11e9-9e75-7fbe3aeea618.JPG" width="300">

This is the "new" proposed look (with star icons):

<img src="https://user-images.githubusercontent.com/4005543/61443948-be7c4500-a94a-11e9-9b6d-074c4ca78377.JPG" width="300">

But we could also use checkboxes:

<img src="https://user-images.githubusercontent.com/4005543/61443993-d5bb3280-a94a-11e9-9829-cbf98c709856.JPG" width="300">

What do you guys think?

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

The 🌟 was just something I tried, not a requirement so if we want another symbol that's fine.

Checkboxes isn't good for it can signal that you could choose multiple which is false.

Best regards
Daniel

**Comment by alexhauser** [comment]
Yep, you're right with the checkboxes @kalaspuffar, that could indeed raise wrong expectations.

Should I post a PR with the flattened star version, or do you like the original version better?

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

Really like your version. PR please :)

Best regards
Daniel
