### ISSUE TITLE
Discussion: Purpose of ClearIdentityActivity

### ISSUE THREAD

**Issue by alexhauser** [kalaspuffar/secure-quick-reliable-login#386]
### Discussion:

I stumbled upon `ClearIdentityActivity` while looking for places that still use raster images, but it then made me curious and I took a closer look.

I've noticed that we only ever instantiate `ClearIdentityActivity` from `BaseActivity.showClearNotification()`, which itself is unused since we've removed the "Clear QuickPass"-notification. If I didn't miss anything, this means that this activity is effectively unused as well. Is that correct?

However, as it seems, this activity is the only place where we ever clear the `KeyStore`-entry named `quickPass`, which gets created in `SQRLStorage.encryptIdentityKeyBiometric()`.

Hence my question and a call for discussion:

Shouldn't the clearing of the `KeyStore`-entry be moved to `SQRLStorage.clearQuickPass()` to ensure that the key is reliably destroyed along with its corresponding shared preference entry every time the QuickPass gets cleared? 

I guess we could then also get rid of `ClearIdentityActivity`.

@kalaspuffar , can you please let me know if I'm on the right track here or if I missed something?

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

Sounds like you are on the right track. This activity have been left since we had a notification that triggered QuickPass removal.

If we have something that isn't cleared with the clear QuickPass then it should be added.

Best regards
Daniel
