### ISSUE TITLE
Properly handle cancelling a CPS authentication

### ISSUE THREAD

**Issue by alexhauser** [kalaspuffar/secure-quick-reliable-login#388]
### Enhancement.

Steve describes on page 9 of the new `SQRL Operating Details` document how to properly handle an aborted CPS authentication:

> **What if no cancel parameter?**
... 
In this case, the SQRL client should return a simple webpage to the browser to show its users something like: “You have cancelled the SQRL sign-in. Please press your web browser’s BACK button to return to the previous login page. That simple page might also contain JavaScript to pop the browser’s page history stack to automatically return the user to the previous page.
... 

We currently redirect the browser to `www.google.com`.

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

Great catch. I've not read the text yet as it's still in it's final revisions and I just returned from my vacation :)

I don't know what page we should redirect to so I choose Google back in the day as it probably would be present. Creating a simple html page with information could be an easy fix though :)

Best regards
Daniel

**Comment by alexhauser** [comment]
> Creating a simple html page with information could be an easy fix though :)

Yep, I'm on it!

**Comment by alexhauser** [comment]
How about this, @kalaspuffar ?

![auth_aborted](https://user-images.githubusercontent.com/4005543/61576026-6e30ee80-aad4-11e9-8f49-d4f52d9df9b0.jpg)

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

The read in the title might be a bit deep. Then again the background is also deep. So maybe a lighter color would lighten up the page a bit?

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi @kalaspuffar, 

I wanted to stick with the SQRL logo's "signature" colors. That's why I chose that blue and the white. But I agree on the red being a bit deep. I'll experiment a bit with the title color and get back with a suggestion.

Best regards,
Alex

**Comment by alexhauser** [comment]
Hi @kalaspuffar ,

I think this should do it:

![auth_aborted2](https://user-images.githubusercontent.com/4005543/61587728-9d586600-ab8f-11e9-98ca-695643f12201.jpg)
