### ISSUE TITLE
Add menu icons

### ISSUE THREAD

**Issue by alexhauser** [kalaspuffar/secure-quick-reliable-login#390]
### Proposed enhancement

What do you guys think about adding icons to our (overflow) menus?

<img src="https://user-images.githubusercontent.com/4005543/61576414-172e1800-aada-11e9-8d47-7aaae1f6e747.JPG" width="300">

Or using the accent color?

<img src="https://user-images.githubusercontent.com/4005543/61576486-f6b28d80-aada-11e9-955e-a02cf9e5f0df.jpg" width="300">

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

I like both versions. If we want to make the choices prominent, and we want people to associate the icons with the choice quickly, then the accent colors are great.

If we, on the other hand, want to de-emphasize the icons, then we can have the gray ones, so they are there as a visual help but don't steal focus from the text.

Maybe this is something we could ask @silversword or someone on the forum to get more perspectives?

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi @kalaspuffar , @sengsational and @sesam ,

it's moving slowly in the forums these days, and there are still no reactions to our call for help regarding the ux topic.

So I'd suggest we go ahead and keep on improving the current design/ux to the best of our abilities, until we find someone who is capable and willing to help (and also willing to put in some elbow grease, not only fancy words).

If everyone agrees, I'll post a PR with the gray menu icons, in order to keep moving and improving.

Best regards,
Alex

**Comment by sesam** [comment]
My humble opinion is to go with gray/not saturated icons as they "are one" with the text to the right of the icon.
Adding a nice-to-have: increase contrast, i.e. darker rather than lighter gray (for the daylight-theme), just in case someone uses this app in bad lighting conditions and/or seeing impairments.
I also wonder how this PR affects the dark theme?

**Comment by gwes** [comment]
Personal opinion... Seeing both side by side, the gray ones look like they are disabled.

**Comment by alexhauser** [comment]
> I also wonder how this PR affects the dark theme?

The current gray works fine on both the light and the dark theme. But if we want to make them darker, it wouldn't be a problem to do so only for the light theme, and leave them as is for the dark theme.

> Personal opinion... Seeing both side by side, the gray ones look like they are disabled.

Yeah, good point, even though I think as long as the text isn't that light, too, it doesn't look too much like it is disabed. I'll post another variant with the contrast increased for the icons.

**Comment by alexhauser** [comment]
Do you guys think this is better?

<img src="https://user-images.githubusercontent.com/4005543/61723133-da794f80-ad6b-11e9-9623-169a6136487e.jpg" width="300">

**Comment by sesam** [comment]
The last is very clear to read. Nice!
