### ISSUE TITLE
Discussion: Rename SimplifiedActivity

### ISSUE THREAD

**Issue by alexhauser** [kalaspuffar/secure-quick-reliable-login#393]
### Enhancement:

Now that we've removed a lot of the legacy activities and code, I think it would be appropriate to rename `SimplifiedActivity` to something that better fits its current role.

I would suggest renaming it to `MainActivity`.

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

Sounds like a great idea. We don't need to keep legacy, and this is the main activity that you will go to on launch most of the time.

But open to suggestion on other names. Any suggestions @sengsational or @sesam ?

Best regards
Daniel

**Comment by sesam** [comment]
> There are only two hard things in Computer Science:
> 1. Naming things...
> 

Jokes aside, the suggested MainActivity looks good to me :)
