### ISSUE TITLE
Improve IdentityManagementActivtiy

### ISSUE THREAD

**Issue by alexhauser** [kalaspuffar/secure-quick-reliable-login#401]
### Enhancement:

Improve UX of `IdentityManagementActivtiy`:

Option 1: Only add top hero icon, but leave buttons:

<img src="https://user-images.githubusercontent.com/4005543/61890954-eb12fc80-af08-11e9-93f1-ccdbf90829b2.jpg" width="300">

Option 2: Add top hero icon and use a `FloatingActionButton` with a popup menu instead of the standard buttons:

<img src="https://user-images.githubusercontent.com/4005543/61890973-f534fb00-af08-11e9-9497-172ff92ad845.jpg" width="300">

<img src="https://user-images.githubusercontent.com/4005543/61890977-f9611880-af08-11e9-9464-b170e72e4807.jpg" width="300">

@kalaspuffar , @sengsational, @sesam and all others that are interested:
Do you like the proposed changes, and if yes, which option do you prefer?

**Comment by kalaspuffar** [comment]
Hi @alexhauser, @sesam and @sengsational 

I say keep the buttons or switch to the floating action button.

But if we switch then perhaps we use the screen size better if we list all identities and give them all buttons for changes and then selecting them via a radio button approach. What do you think?

Floating action buttons are usually used to add items to lists.

Thoughts?

Best regards
Daniel

**Comment by sesam** [comment]
I see, create new/import does make more sense if you can also see how many identities you already have.

On the other hand, maybe we want to encourage users to not use several identities? I guess it's already moved one more click away from the front
It was also mentioned it might be good to hide the names and amount of identities.

My recommendation is to use this PR as is, and I'm inviting to discuss this from another angle here:  https://github.com/kalaspuffar/secure-quick-reliable-login/issues/405
