### ISSUE TITLE
Coloration issues.

### ISSUE THREAD

**Issue by kalaspuffar** [kalaspuffar/secure-quick-reliable-login#402]
Hi @alexhauser 

Just checking if this is per design to have another gray in the background of the rekey text. I see that we have similar text background on the create new identity flow so it might be my fault :)

![gray](https://user-images.githubusercontent.com/1424084/61905196-cd558f80-af28-11e9-8b39-2959b5c1151a.png)

**Comment by kalaspuffar** [comment]
Seems the same gray box is present on the done page.

![gray_done](https://user-images.githubusercontent.com/1424084/61905446-68e70000-af29-11e9-81dd-7202e22f19c8.png)

**Comment by kalaspuffar** [comment]
![diff_color](https://user-images.githubusercontent.com/1424084/61905560-a6e42400-af29-11e9-8aeb-53b7695c8d79.png)

**Comment by kalaspuffar** [comment]
![missing_cps](https://user-images.githubusercontent.com/1424084/61905704-06423400-af2a-11e9-9b7d-5bfdb955ee58.png)

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

I don't know if you were notified by this issue as I had to edit it.

I think I've found all instances of this color mismatch. I think you solved a similar issue so you might be quick on it :)

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi @kalaspuffar,

weird, I haven't seen this issue anywhere during my testing on different virtual and physical devices.

Can you please let me know on which device/api you're seeing this?

Thanks, Alex

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

Might be that the Android_x86 image is special I don't know. I've had a lot of bad experience with different emulators from Android Studio. Rebooting my machine and so on so I'm running a specially crafted version of Android. Might be something people using their own build Android might encounter.

https://www.android-x86.org/

We can let it go if you like and release as is or I can look into it if you don't know directly the cause. I think we saw a similar issue earlier and you corrected that one quickly.

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi @kalaspuffar,

I actually don't have a quick idea for this one. You could try explicitly setting the background for the affected `TextView`s to transparent and see if that changes anything. 

Best regards,
Alex

**Comment by alexhauser** [comment]
It's interesting, too, that in your last screenshot, it looks like the whole `ScrollView` is affected, not only the `TextView` like on the other ones.

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

I think I will close this issue, it's a unique issue that probably won't affect that many users and I can't really find a good fix for it without hardcoding a lot of colors.

Best regards
Daniel
