### ISSUE TITLE
Improved clarity on password usage.

### ISSUE THREAD

**Issue by kalaspuffar** [kalaspuffar/secure-quick-reliable-login#404]
### Feature request.

*Short description of the feature*

suggestion from user: 
provide more context for what password the app requests when the user attempts to log into a website. is this a website specific password or an SQRL identity password or SQRL vault (app) password or what?

**Comment by alexhauser** [comment]
Valid point. Should be easily solvable by adding another info icon to the right of the password field which will show a help text regarding the identity password when it's being tapped on.

Or does anyone have a better implementation idea?

**Comment by sengsational** [comment]
This was my very first observation when trying the app for the first time (https://sqrl.grc.com/threads/just-a-ramble-on-my-first-day-with-sqrl.336/).

>  The app flipped back out of camera mode. Then it's asking for a "password". Here I found myself wondering "does this app think I already have a password for sqrl.grc.com? And I'm thinking "whoa, I'm not giving my SQRL master password to this hinky forum site, who knows who this Gibson character is, anyway" ;) Seriously, the point I'm trying to make is that instead of "password", it should probably be labeled "SQRL Master Password" and have an info thing that pops up and says "your master password is used to decrypt your identity...it won't leave your phone". 

I like the idea of a more info user action that will clarify what's happening with the password.

**Comment by alexhauser** [comment]
OK, so we're talking about two different scenarios here: 

The OP was referring to the password field on the login screen, while @sengsational is talking about creating the identity password in `SaveIdentityActivity`.

Both of those should be addressed, I guess.
