### ISSUE TITLE
Minimise personally identifiable info & simplify on-boarding.

### ISSUE THREAD

**Issue by sesam** [kalaspuffar/secure-quick-reliable-login#405]
### Feature request.

When creating a (or at least *the first*) identity, can we set the name/title of this identity automatically?

It would simplify the get-started process for new users who want to do everything right and feel they need to read and research before deciding. The first default identity name could be used as a way to nudge users into using just one identity. Should simplify on-boarding process too!

On the other hand, once we have a, say, "SQRL master identity" or "Primary" or something, then the next created or imported identity could be named "(Created/Imported) $date $time UTC" maybe as a suggestion, then let the user change it.

The above comes from the https://github.com/kalaspuffar/secure-quick-reliable-login/issues/401 and a vague memory that we might want to hide the user's stored identities ( names and amount) or slightly decrease shoulder surfing risks.

**Comment by kalaspuffar** [comment]
Hi @sesam 

First identity get the name default.

Best regards
Daniel

**Comment by sesam** [comment]
I'll take the prerelease for a spin and see if there's anything else related to P.I.I. and keeping the app from leaking info needlessly, and welcome any more ideas around this.

I'm also curious what you all think of "default" or if you have considered other names for the first identity. I guess "default" might make the user think it's what gets chosen per default when you close and reopen, at least that's how programmer-targeted tools often do it. Should we brainstorm on alternative names for the first identity? What does the windows client do here? (I could hijack some family computer and try it out I guess :))

**Comment by alexhauser** [comment]
I would go for

- "Identity1"
- "Identity2"
- ...

This could nicely be translated (iirc, we have the string "identity" already) and would be somewhat self-describing when the user actually sees the name for the first time (when visiting identity management or when creating/importing a second identity).

**Comment by alexhauser** [comment]
@sesam, please also note that in the current version of the app, you'll find that the name of the currently active identity is being hidden everywhere except from the identity management screen, as long as there is only one identity present.

**Comment by sengsational** [comment]
We can have spaces, right?  I like "My SQRL Identity", then, if they create of load another one, go with "Identity2", etc.  I'm afraid if they see "Identity1", they'll think they need more than one.

**Comment by kalaspuffar** [comment]
I've actually called my real identity "this is me" :)

**Comment by alexhauser** [comment]
> I'm afraid if they see "Identity1", they'll think they need more than one.

The beauty of the current design is that they actually won't see the name of the first identity unless they add a second one or specifically go to the identity management screen. 

Still, I like you suggestion Dale, but find "*My SQRL Identity*" to be a little too verbose and also not good-looking. How about skipping the "SQRL" and just doing "*My Identity*"?

**Comment by kalaspuffar** [comment]
Hi @sesam 

Do you feel that we addressed the issue? Or should we discuss further in this issue?
As you see we have addressed the naming and @alexhauser have added a new issue for more changes to the onboarding.

Best regards
Daniel

**Comment by sesam** [comment]
🎉 Nice! Looks like this is well enough for what I was thinking about.
