### ISSUE TITLE
Discussion: Remove "SQRL - " prefix from activity titles

### ISSUE THREAD

**Issue by alexhauser** [kalaspuffar/secure-quick-reliable-login#406]
### Discussion:

A contributor on POEditor commented that the activity titles shown in the action bar are sometimes confusing in the German language because of our "SQRL - " prefix is not always immediately recognizable as such. 

He made the suggestion to substitute the dash with a colon, so that it would for example read "_SQRL: Rettungscode eingeben_" instead of "_SQRL - Rettungscode eingeben_", which would already be an improvement, and we could do that locally only for the German language if we wished to.

However, I had thought about this topic also before, and always wanted to discuss it at the right oppurtunity.  To me, it feels like we should drop the "SQRL"-prefix all together and just show the ACTUAL activity purpose. This would increase clarity and would also solve some space issues which are present on low resolution devices and/or long translation strings.

@kalaspuffar and others, what do you guys think?

**Comment by sengsational** [comment]
I agree that if we're giving the user directions, having a "SQRL - " prefix isn't helpful.  I think optimally there would be a way to give the user more info, so the "headline" would be "Enter rescue code" (without the prefix), and there might be a little "?" icon that, if pressed would elaborate with something like "Your SQRL rescue code was provided to you when you first created your identity.  Please find the paper you saved..."

**Comment by alexhauser** [comment]
Great, seems we're all on the same page here.

I'll remove the prefix from the German translation. @kalaspuffar, will you handle English (and possible other languages)?

@sengsational , will you look into the idea with the help icon next to the activity title? The easiest solution would be to use the "normal" overflow menu and have one "context help" item to always display on the action bar as an icon using `android:showAsAction="always"`, and override its content on-the-fly on each activity. But this may look too much like a general "help" button instead of sensitive to the context of the current activity.

**Comment by kalaspuffar** [comment]
Hi @alexhauser and @sengsational 

I've removed all prefixes from the titles in POEditor.

It's a little bit strange that we have multiple ones that are prefixed with "title_" but I found one instance that used the postfix of "_heading" instead. I've changed both in all languages though.

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi @kalaspuffar and @sengsational ,

> we have multiple ones that are prefixed with "title_" but I found one instance that used the postfix of "_heading" instead

Yeah, I've noticed this too while changing the German titles, but did not dare to change this on GitHub since I don't know if this would work with POEditor and the scripting involved.

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

If it should be a title then we can change the name in code and add the English translation and then I can handle the Poeditor. Either renaming or making a copy of the string with the new name.

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi @kalaspuffar and @sengsational ,

I guess it was supposed to be an activity title, but it ended up not being used. Instead, in `EnableQuickPassActivity`, the very similar `quickpass_enable_message` was used as activity title, which says "*Enabling QuickPass*" instead of "*Enable QuickPass*".

However, I think we should fix this. By that I mean rename the title string's name to "title_quickpass_enable" and to also use this one as the activity title for `EnableQuickPassActivity`. Is that OK with you, Dale?

Best regards,
Alex

**Comment by sengsational** [comment]
Yes.  I noticed this discrepancy before, but was trying to concentrate on something else, I suppose, to get it fixed.  But I agree with the fix that's been updated.
