### ISSUE TITLE
Simplify naming when creating a new identity

### ISSUE THREAD

**Issue by alexhauser** [kalaspuffar/secure-quick-reliable-login#414]
### Enhancement:

In issue #405, @kalaspuffar answered regarding the naming of identities:

> First identity get the name default.

This is true only when the first identity is being **imported**. The situation is different when the first identity is being created from scratch. In this case, we currently always ask for an (optional) identity name:

<img src="https://user-images.githubusercontent.com/4005543/62491778-2c3ec280-b7cd-11e9-8ee3-df43e8761e05.jpg" width="300">

My suggestion would be to completely remove the *Identity name* field from `SaveIdentityActivity` and handle naming like we do it on import: If it's the first identity, just silently use the (new) default identity name, and if not, then send them over to the `RenameActivity` in the last step.

What do you guys think?

**Comment by kalaspuffar** [comment]
Hi @alexhauser, @sesam and @sengsational 

I think this change is reasonable. If we feel different in the future we could move to another more streamlined process but removing the optional name from the creation process might be something that will increase adoption as every extra introduced step will make people hesitant. For instance:

"I want to pick a name but don't know what is appropriate but it's optional so I might want to or should I?"

If the option is not presented we give the user a more streamlined experience and they can later find that you can actually rename it if you like.

Then again for more experienced users we might have the "problem" that they have a name already in another client and import it. Then they want to keep their name from the other client. But we already have that issue so it won't change with this change.

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi @kalaspuffar ,

thanks for your feedback, you summarized exactly what I was thinking as well. 

As for the "power user" case, it would be easy to add a global settings toggle like "*Always offer naming identities*", which we would check upon import/creation and if it's activated we always launch the `RenameActivity`.

Best regards,
Alex

**Comment by sengsational** [comment]
Default name (streamlined process) on both new creation and import sounds like the best approach. 

I'm not sure a setting is necessary; if they're a power user, they'll know how to rename.  As soon as they have two or more identities, the application should make it obvious that renaming is an option.  I haven't played with multiple identities in a long time, so just talking conceptually.
