### ISSUE TITLE
New back button

### ISSUE THREAD

**Issue by kalaspuffar** [kalaspuffar/secure-quick-reliable-login#419]
### Feature request.

After seeing the back button we implemented for the Identity Management page. I think we should fix so we have a consistent layout. So where ever applicable we should implement the new way of enabling back for users.

I believe that the back button is optional on devices so giving the user a consistent alternative to going back to the previous page seems like a good addition. What do you think @sesam, @sengsational and @alexhauser?

Best regards
Daniel

**Comment by sengsational** [comment]
I'm thinking that rather than do each activity, we can add some code to `CommonBaseActivity` that would put the 'back' arrow in the title bar.

I added this to `CommonBaseActivity.onCreate()`:

        ActionBar actionBar = getSupportActionBar();
        if (actionBar != null) {
            actionBar.setDisplayHomeAsUpEnabled(true);
            actionBar.setDisplayShowHomeEnabled(true);
        } 

And added this method to `CommonBaseActivity`:

    @Override
    public boolean onSupportNavigateUp(){
        onBackPressed();
        return true;
    }

And it seemed to do what we want: back arrows that don't depend on the phone's back button.  We'd probably want to turn it off on the main screen, though.

**Comment by kalaspuffar** [comment]
Hi @sengsational 

Great suggestion. I want to remove them from screens that are a part of guides as well. Or they need to jump the user back to the right screen, outside of the guide. 

For instance, if you have started an identity creation you can't back to the previous step you need to start over.

Other than that you can create a pull request with this suggestion if you like :)

Best regards
Daniel

**Comment by alexhauser** [comment]
Yes @sengsational, if we really do want a back button on every activity, that would be the way to do it. 

I don't really have a strong opinion on the topic, so I'm gonna let you guys decide how to go on with this.

Oh and by the way, Dale, your screenshot tells me that you're a few commits behind the current status quo, so you might consider pulling all the latest changes before posting a PR.

Cheers, Alex

**Comment by sengsational** [comment]
I'll take a look and see if I can find all the instances of "back" functionality in the guides.  And certainly will grab the most up-to-date code before making any significant changes...my original post here was just a "quickie" to see if it would work.
