### ISSUE TITLE
Ability to navigate to identity management parent from identity management child activities

### ISSUE THREAD

**Issue by sengsational** [kalaspuffar/secure-quick-reliable-login#421]
### Identity Management shows in the options menu in child activities

*Short description of the issue*
The options menu allows users to go to "identity management" from activities which are spawned from the activity management activity itself. 

*Expected behavior*
Users would not be given the opportunity to go to identity management if they were already performing some identity management activity.

*Actual behavior*
Users can select "identity management" from export identity activity, for example, then the activity stack gets confused.

*Steps to reproduce*
For example, go into export identity, then use the options menu to select "identity management".  Now it the 'back' button on the phone or in the action bar.  Focus will return to the export identity (weird).  If the user was not given the opportunity to go to the base identity management from a child activity management activity, then this wouldn't happen.

*Proposed solution*
Remove "identity management" from the options menu in child activities.  In `BaseActivity.onCreateOptionsMenu()`, we already have `action_identity_management` set to not visible.  Activities that are considered children to identity management should also be included there.

**Comment by alexhauser** [comment]
I fully agree!
