### ISSUE TITLE
Identity text validatation doesn't match

### ISSUE THREAD

**Issue by sengsational** [kalaspuffar/secure-quick-reliable-login#425]
### Identity text validatation doesn't match if printed with password

*Short description of the issue*
If a user attempts to import an identity, they are presented with the identity in text format that doesn't match if they originally printed their identity with the password included.

*Expected behavior*
The user should not be asked to compare text unless they scanned a QR code identity without embedded password.

*Actual behavior*
The user is asked to compare the text on the screen of the device with the paper identity, which may not match. 
>Please verify that the rescue data presented below corresponds to the data printed on your key page.

*Steps to reproduce*

- Create an identity and when asked to print, print the identity with password.
- Scan the QR code
- Notice the text on the page does not match (unexpected).

**Comment by alexhauser** [comment]
Hi @sengsational ,

I cannot reproduce this on my end. When I follow the given procedure, the identity texts do match. I'll do a little more testing to see if I can make it fail.

Best regards,
Alex

**Comment by sengsational** [comment]
Sorry for putting you through that testing Alex; I think it was a false alarm.  

The printed SQRL page that I was using during that test was an old one (from mid-February).  So I suspect that using a more up-to-date printed identity page will not cause the issue because the code that generates the printed page has been updated.  

 My mistake was thinking that the page I was testing with was a recently generated page.  Again, I regret having caused you to spend time on this.

**Comment by alexhauser** [comment]
No problem at all, Dale! Glad that everything works as expected. 
Alex
