### ISSUE TITLE
Fix Alt-Id input field not being recongizable as such

### ISSUE THREAD

**Issue by alexhauser** [kalaspuffar/secure-quick-reliable-login#432]
### Issue or error solving.

See https://sqrl.grc.com/threads/android-v1-5-0-alpha.849/post-7301

Dave mentions regarding the Alt-Id input text field:
> I looked right at that (without reading the words) and assumed it was a column heading for the radio buttons!! D'OH!!

Maybe we should give the text field a different background color or something. What do you guys think?

**Comment by shanedk** [comment]
Maybe if it had a radio button next to it to make it look like one of the options? It could automatically activate when you start typing, and you could cancel the Alt-ID by clicking it off without having to delete the text.

**Comment by alexhauser** [comment]
That's impractical Shane, because the Alt-Id can (and must be able to) be used together with any of the account options below. In other words, you must be able to for example disable an account using an Alt-Id. And having two radio buttons activated at the same time is a no-no.

I was thinking about simply giving the text field a white background, so that it stands out a little more against the gray background (with matching adaptations for the dark theme of course).
