### ISSUE TITLE
Introduction Guide / Wizard

### ISSUE THREAD

**Issue by kalaspuffar** [kalaspuffar/secure-quick-reliable-login#435]
### Feature request.

*Short description of the feature*
Creating a short introduction wizard/guide that will replace the block of text we have on our introduction page.

I sat down today and created some screens that explain my thoughts. I'm no designer so the balance of the pages is all over the place but I hope that the general idea is clear enough.

![page1](https://user-images.githubusercontent.com/1424084/64926619-ee877d80-d7ff-11e9-9be8-3f1052242aaf.png)
![page2](https://user-images.githubusercontent.com/1424084/64926620-ee877d80-d7ff-11e9-811b-2e03e64b2ae3.png)
![page3](https://user-images.githubusercontent.com/1424084/64926621-ee877d80-d7ff-11e9-8e0d-0b58b09b4fdb.png)
![page4](https://user-images.githubusercontent.com/1424084/64926622-ee877d80-d7ff-11e9-8894-3b18210f3503.png)

Thoughts @sengsational, @sesam and @alexhauser?

Maybe someone with more graphical skills could add some illustrations to convey the information in a more instructive way. Perhaps we want different introduction bullets or in a different order.

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi @kalaspuffar,

I really like the idea of breaking up the huge block of intro text into only a few nice looking, small and easily digestable snippets.

I also like the general look-and-feel of your drafts. I think if we had someone to give it a final touch-up and maybe even add some vector art, this could be a perfect onboarding experience.

**Comment by sesam** [comment]
This feels like a great idea! I think it's worth to take some iterations on the texts and ordering too. My first impression was WOW! Reading it two more times, I'm starting to think how it could be reorganised to keep what users care about up front. Maybe also make it more "selling" and keep what's meant for more technically minded people later in. So those who want to get started can learn just a little bit then get going, while curious know-it-alls go all the way through and get more details.

We could use the time when the user is reading to prepare other things behind the scenes. Maybe create and store the first identity with strong = slow encryption.
The other, very outdated, android SQRL app creates an identity before you reach the first screen, and crypto-wallets often create keys automatically, and then nag the user to create a backup, or even make it impossible to use the wallet without first making a backup, the proper way.

So my $0.20 :) is that we should consider this in the light of the full first-time on-boarding experience. Writing a text that explains all the things the first-time user needs to do to get started is usually a good (painful) experience, where those responsible for the app quickly figure out things that can be improved. I'm kind of tempted to try something like that, maybe try writing a stream-of-thought monologue of an imagined user that just heard from a friend that SQRL is good stuff, so someone arriving in the Play Store with high expectations of coolness.

**Comment by sesam** [comment]
I got started on this, writing down things from the viewpoint of a first time user.
https://docs.google.com/document/d/1teUDIfglz2SrPBHx1mWAlA2ig0sCuXSiceK31lQvPhY/edit?usp=sharing
The crucial second part, actually starting to use the app, is work-in-progress.

**Comment by kalaspuffar** [comment]
Hi @sesam 

Great work, the application is now published on google play production-ready so you should be able to find it without signing up for the alpha release.

Best regards
Daniel
