### ISSUE TITLE
Update rescue code page to new design.

### ISSUE THREAD

**Issue by kalaspuffar** [kalaspuffar/secure-quick-reliable-login#438]
The rescue code page does not have the explaination why we should keep the page.

**Comment by alexhauser** [comment]
Hi @kalaspuffar,

are we talking about the print version of the rescue code page here?

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

Correct, I saw Steve's new layout during the Meetup here in Sweden and I did not want to interrupt the talk with a lengthy report but still remember it as a to-do.

The print page today is only the code in red which is a bit sparse :)

Best regards
Daniel

**Comment by alexhauser** [comment]
Ok, thanks! I'll look into this.
Cheers, Alex

**Comment by alexhauser** [comment]
I basically copied Steve's layout and texts, but also added our existing footer design:

![rescue_code_print](https://user-images.githubusercontent.com/4005543/65764925-1b546280-e127-11e9-8493-1faec6796bcc.jpg)

Any suggestions or change requests?

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

Looks great! I just want us to be compliant with the reference client and make it clear to users that this page is important. Our earlier design was quite lacking. 

Great work.

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi @kalaspuffar,

I totally agree! 

I'll clean things up and post a PR asap. In the PR we can discuss the actual implementation (I tried to avoid duplicating code from `IdentityPrintDocumentAdapter` and instead breaking everything out into reusable chunks) - but let's talk about that when I post the actual code.

Best regards,
Alex
