### ISSUE TITLE
Implement support for tif = 0x200

### ISSUE THREAD

**Issue by kalaspuffar** [kalaspuffar/secure-quick-reliable-login#442]
### Feature request.

Add a message when tif response is 0x200 similar to the reference client.
https://www.grc.com/dev/Superseded-Identity-Detection.png

**Comment by alexhauser** [comment]
Hi @kalaspuffar,

as a first step, I have created the activity layout that we could be showing upon receiving a TIF 0x200 error:

Day mode:

<img src="https://user-images.githubusercontent.com/4005543/68993283-91975a80-0876-11ea-867f-e0f2e28724c5.jpg" width="300">

Night mode:

<img src="https://user-images.githubusercontent.com/4005543/68993285-9eb44980-0876-11ea-9ec5-ef9ea94c86b5.jpg" width="300">

Any feedback is welcome.

Best regards,
Alex

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

Great work, I really like the design. Do you want me to do the back end work or will you?

Best regards
Daniel

**Comment by alexhauser** [comment]
Thanks, @kalaspuffar,

I've just posted a PR which only adds the layout.
I'll look into the backend work and get back to you if I need guidance.

Cheers, Alex
