### ISSUE TITLE
Allow identity import using rescue code also for password-based exports

### ISSUE THREAD

**Issue by alexhauser** [kalaspuffar/secure-quick-reliable-login#446]
### Feature request.

See the full discussion here, https://sqrl.grc.com/threads/adding-identity-without-password.1010/, where Paul Farrer made a good observation:

> The rescue code is intended to be written down and saved in a secure place. The password is intended to be remembered and not written down. One purpose of the rescue code is to recover from a forgotten password. A backup that can only be restored with a password is more at risk of being unusable than one that can be restored with a rescue code.

> Given that a rescue-code-recoverable backup is a subset of a password-recoverable backup, the client could allow the user the option to import a password-recoverable backup either way.

I guess this is something that could be helpful for people in some situations. This is why I suggest we should add this functionality to the Android client.

What do you think, @kalaspuffar ?

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

I don't know if I follow you. If you scan a QRCode or type a text string in for importing an identity. You have the option "Forgot your password?". And that gives you the option to import with your rescue code and set a new password.

Or have I missed some points in the original discussion?

Best regards
Daniel

**Comment by alexhauser** [comment]
Oh, wow, I didn't even notice that we've got that covered already. Cool!
Closing the issue now.

Best regards,
Alex
