### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [kalaspuffar/secure-quick-reliable-login#486]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by mondlicht-und-sterne** [comment]
Since the issue dates back a long time - can you just close
the issue? Thank you, my initial Issie was also just information.

**Comment by kalaspuffar** [comment]
@mondlicht-und-sterne I can close it if you want. I'm not in charge of the F-Droid release so I can't do anything there.

**Comment by mondlicht-und-sterne** [comment]
OK, you can close the issue.

That was just information.
Some people have switched on discussions, otherwise I would have written it down.
