### ISSUE TITLE
Identity Management State Bug

### ISSUE THREAD

**Issue by JamesonNetworks** [kalaspuffar/secure-quick-reliable-login#487]
### Issue or error solving.

*Short description of the issue*

When a user is in Identity Management, if they go to Create Identity, and then drop back to Identity Management wiithout creating an ID, we already have called cleanIdentity on the currently used identity. When you return to the screen, if you try to manage the identity, the UI will have incorrect information displayed to the user.

*Expected behavior*

The information should still reflect the current identity

*Actual behavior*

The information represents the clean identity which has been mutated

*Steps to reproduce*
![Screen Shot 2021-02-28 at 4 19 42 AM](https://user-images.githubusercontent.com/878987/109413616-5d1cb480-797c-11eb-9624-d785a07c66bd.png)
![Screen Shot 2021-02-28 at 4 19 50 AM](https://user-images.githubusercontent.com/878987/109413623-5f7f0e80-797c-11eb-8ab2-15029ceccf57.png)
![Screen Shot 2021-02-28 at 4 19 58 AM](https://user-images.githubusercontent.com/878987/109413621-5ee67800-797c-11eb-92f8-228ee45cdcb7.png)
![Screen Shot 2021-02-28 at 4 20 12 AM](https://user-images.githubusercontent.com/878987/109413620-5e4de180-797c-11eb-81ec-4704d9585ec9.png)

**Comment by alexhauser** [comment]
Totally able to reproduce! Thanks for the comprehensive report and for even suggesting a fix, @JamesonNetworks!
We'll take a look at the PR asap and get back to you with a review.

Cheers, Alex

**Comment by JamesonNetworks** [comment]
> Totally able to reproduce! Thanks for the comprehensive report and for even suggesting a fix, @JamesonNetworks!
> We'll take a look at the PR asap and get back to you with a review.
> 
> Cheers, Alex

Thank you guys for all the work! SQRL login is amazing.
