### ISSUE TITLE
Caps lock issue

### ISSUE THREAD

**Issue by r0adawg** [kalaspuffar/secure-quick-reliable-login#92]
### Feature request.

*Short description of the feature*

*Use cases*

### Issue or error solving.

*Using the button 'Use Identity' to scan QR code, Password field defaults to caps entry for every character.*

*Expected behavior is to not use caps by default.*

*sequence defaults keyboard to enabling caps lock.*

*visit 'https://www.grc.com/sqrl/demo.htm' and open sqrl app on android. Tap button 'use identity' to scan qr code.  Verify correct url and tap password field.  Note state of caps lock or shift key.*

**Comment by kalaspuffar** [comment]
Thank you for finding this one. Great catch. Really strange that textAllCapitalized was set on that field.
